---
# tasks file for roles/i3status-rs

- name: Create i3status-rs config directory
  become: yes
  become_user: "{{ user_id }}"
  file:
    path: "{{ user_config_dir }}/i3status-rs"
    state: directory

- name: Generate i3status-rs config files
  become: yes
  become_user: "{{ user_id }}"
  template:
    src: "{{ item }}.j2"
    dest: "{{ user_config_dir }}/i3status-rs/{{ item }}"
    force: yes
  loop:
    - config-sm.toml
    - config.toml

- name: Prepare i3status-rs config files
  replace:
    path: "{{ user_config_dir }}/i3status-rs/{{ item.0 }}"
    regexp: "{{ item.1.regexp }}"
    replace: "{{ item.1.replace }}"
  loop: "{{ configs | product(replaces) | list }}"
  vars:
    - configs:
      - config-sm.toml
      - config.toml
    - replaces:
      - { regexp: '({)', replace: '\1\1'  }
      - { regexp: '(})', replace: '\1\1'  }
      - { regexp: '@@(.+)@@', replace: '{\1}'  }
  when: theme_name == "wal"
