---
# tasks file for roles/i3status-rs

- name: Create i3status-rs config directory
  become: yes
  become_user: "{{ user_id }}"
  file:
    path: "{{ user_config_dir }}/i3status-rs"
    state: directory

- name: Generate i3status-rs config files
  become: yes
  become_user: "{{ user_id }}"
  template:
    src: "{{ item }}.j2"
    dest: "{{ user_config_dir }}/i3status-rs/{{ item }}"
    force: yes
  loop:
    - config-sm.toml
    - config.toml
