icons = "awesome"

[theme]
name = "modern"
[theme.overrides]
idle_bg = "#282828"
idle_fg = "#EBDBB2"
info_bg = "#458588"
info_fg = "#282828"
good_bg = "#98971A"
good_fg = "#282828"
warning_bg = "#D79921"
warning_fg = "#282828"
critical_bg = "#CC241D"
critical_fg = "#282828"
separator = "\ue0b2"
# seperator_bg = "auto"
# separator_fg = "auto"
alternating_tint_bg = "#111111"
alternating_tint_fg = "#000000"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "net"
device = "wlp2s0"
ssid = false
signal_strength = true
ip = true
speed_up = false
speed_down = false
graph_up = false
speed_down = false
interval = 5

[[block]]
block = "net"
device = "tun0"
speed_up = false
speed_down = false
graph_up = false
speed_down = false
# hide_missing = true
# hide_inactive = true
interval = 5

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}°C"
chip = "*-isa-*"

[[block]]
block = "load"
format = "{1m}"
interval = 1

[[block]]
block = "memory"
format_mem = "{Mug}GB/{MTg}GB {Mupi}%"
format_swap = "{SUg}GB/{STg}GB {SUpi}%"
display_type = "memory"
icons = true
clickable = true
interval = 5

[[block]]
block = "backlight"

[[block]]
block = "sound"
step_width = 5
show_volume_when_muted = true

[[block]]
block = "uptime"

[[block]]
block = "time"
format = "%a %m/%d/%Y %r"
timezone = "US/Eastern"
interval = 5
