# generated by zon2nix (https://github.com/nix-community/zon2nix)
{
  linkFarm,
  fetchzip,
}:
linkFarm "zig-packages" [
  {
    name = "122099facef1728bd1118fac3a9444f5daca7278046e734a25f03f7e20bad2b5cb28";
    path = fetchzip {
      url = "https://github.com/batiati/mustache-zig/archive/6f9f24543c97bdf2c4735769c33ce729d164657a.tar.gz";
      hash = "sha256-/YPISQRXYfd/KaCH/DpFH9WkNfwmxAypekw1vy9QxB4=";
    };
  }
  {
    name = "1220a8b06d4d91ff6e260794fc2a8f729f8c8713c3006611926f3e5dad915e97b36d";
    path = fetchzip {
      url = "https://github.com/00JCIV00/cova/archive/b9f127acfbb689a7f0dd7f1073ad463f55a29afe.tar.gz";
      hash = "sha256-EBCU3X2smzRNN9z0Eomre5/I0Vf7iPm/GOouKW9QvL0=";
    };
  }
]
