version: '3'

services:
  # linux-systemd
  dotfiles_linux_systemd_full: &default
    build: &default_build
      context: .
      args: &default_args
        PROFILE: linux-systemd-full
    image: dotfiles/linux-systemd-full

  dotfiles_linux_systemd_minimal:
    <<: *default
    build:
      <<: *default_build
      args:
        <<: *default_args
        PROFILE: linux-systemd-minimal
    image: dotfiles/linux-systemd-minimal

  dotfiles_linux_systemd_standard:
    <<: *default
    build:
      <<: *default_build
      args:
        <<: *default_args
        PROFILE: linux-systemd-standard
    image: dotfiles/linux-systemd-standard

  dotfiles_linux_systemd_base:
    <<: *default
    build:
      <<: *default_build
      args:
        <<: *default_args
        PROFILE: linux-systemd-base
    image: dotfiles/linux-systemd-base

  # linux
  dotfiles_linux_full: &default
    build: &default_build
      context: .
      args: &default_args
        PROFILE: linux-full
    image: dotfiles/linux-full

  dotfiles_linux_minimal:
    <<: *default
    build:
      <<: *default_build
      args:
        <<: *default_args
        PROFILE: linux-minimal
    image: dotfiles/linux-minimal

  dotfiles_linux_standard:
    <<: *default
    build:
      <<: *default_build
      args:
        <<: *default_args
        PROFILE: linux-standard
    image: dotfiles/linux-standard

  dotfiles_linux_base:
    <<: *default
    build:
      <<: *default_build
      args:
        <<: *default_args
        PROFILE: linux-base
    image: dotfiles/linux-base
