#!/usr/bin/env bash

code-insiders --install-extension bungcip.better-toml
code-insiders --install-extension codehz.chaiscript-syntax
code-insiders --install-extension eamodio.gitlens
code-insiders --install-extension EditorConfig.EditorConfig
code-insiders --install-extension josef.rouge-theme
code-insiders --install-extension jpoissonnier.vscode-styled-components
code-insiders --install-extension kumar-harsh.graphql-for-vscode
code-insiders --install-extension mikestead.dotenv
code-insiders --install-extension ms-python.python
code-insiders --install-extension ms-vscode-remote.remote-containers
code-insiders --install-extension ms-vscode-remote.remote-ssh
code-insiders --install-extension ms-vscode-remote.remote-ssh-edit
code-insiders --install-extension ms-vscode-remote.remote-ssh-explorer
code-insiders --install-extension ms-vscode-remote.remote-wsl
code-insiders --install-extension ms-vscode-remote.vscode-remote-extensionpack
code-insiders --install-extension ms-vscode.cpptools
code-insiders --install-extension nepaul.editorconfiggenerator
code-insiders --install-extension PKief.material-icon-theme
code-insiders --install-extension primalmotion.primal
code-insiders --install-extension rust-lang.rust
code-insiders --install-extension shd101wyy.markdown-preview-enhanced
code-insiders --install-extension sidneys1.gitconfig
code-insiders --install-extension slevesque.shader
code-insiders --install-extension slevesque.vscode-hexdump
code-insiders --install-extension smkamranqadri.vscode-bolt-language
code-insiders --install-extension toba.vsfire
code-insiders --install-extension twxs.cmake
code-insiders --install-extension vscodevim.vim
code-insiders --install-extension xaver.clang-format
code-insiders --install-extension ymotongpoo.licenser
