// Code generated by "marshaler -type PrivilegeLevel -stringer NixString"; DO NOT EDIT.
package privilegelevel

import "encoding/json"

// MarshalJSON implements the json.Marshaler interface for PrivilegeLevel
func (i PrivilegeLevel) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.NixString())
}

// MarshalText implements the encoding.TextMarshaler interface for PrivilegeLevel
func (i PrivilegeLevel) MarshalText() ([]byte, error) {
	return []byte(i.NixString()), nil
}
