" setup Plug
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'itchyny/lightline.vim'
Plug 'tmux-plugins/vim-tmux'
Plug 'edkolev/tmuxline.vim'
Plug 'skywind3000/asyncrun.vim'
"Plug 'w0rp/ale'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'terryma/vim-multiple-cursors'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-surround'
Plug 'editorconfig/editorconfig-vim'
"Plug 'sgur/vim-editorconfig'
Plug 'mattn/emmet-vim'
Plug 'airblade/vim-gitgutter'
Plug 'tomasiser/vim-code-dark'
Plug 'morhetz/gruvbox'
Plug 'mengelbrecht/lightline-bufferline'
Plug 'tpope/vim-fugitive'
Plug 'itchyny/vim-gitbranch'
Plug 'rhysd/vim-clang-format'
Plug 'tpope/vim-vinegar'
Plug 'tpope/vim-commentary'
Plug 'chrisbra/Colorizer'
Plug 'chrisbra/unicode.vim'
Plug 'sheerun/vim-polyglot'
Plug 'ludovicchabant/vim-gutentags'
Plug 'vim-scripts/ReplaceWithRegister'
Plug 'christoomey/vim-titlecase'
Plug 'christoomey/vim-sort-motion'
Plug 'christoomey/vim-system-copy'
Plug 'kana/vim-textobj-user'
Plug 'kana/vim-textobj-indent'
Plug 'kana/vim-textobj-entire'
Plug 'kana/vim-textobj-line'
Plug 'takac/vim-hardtime'
Plug 'easymotion/vim-easymotion'
if v:version >= 800
    Plug 'maralla/completor.vim'
endif

call plug#end()

" lightline
set laststatus=2
set showtabline=2
set noshowmode

" vim-javascript
let g:javascript_plugin_jsdoc=1

" rust.vim
let g:rustfmt_autosave=1

" tmuxline
let g:tmuxline_preset='full'
let g:tmuxline_powerline_separators=0

" asyncrun
"autocmd BufWritePost *.ts,*.tsx AsyncRun -post=checktime npm run format %

" junegunn/fzf.vim
nnoremap <C-p> :Files<CR>
nnoremap <Leader>b :Buffers<CR>
nnoremap <Leader>h :History<CR>
nnoremap <Leader>t :BTags<CR>
nnoremap <Leader>T :Tags<CR>

" emmet-vim
let g:user_emmet_leader_key='<Tab>'
let g:user_emmet_settings={
    \ 'javascript.jsx' : {
    \   'extends': 'jsx',
    \ },
    \ }

" lightline-bufferline
let g:lightline#bufferline#show_number=1
let g:lightline#bufferline#shorten_path=0
let g:lightline#bufferline#unnamed='[No Name]'

let g:lightline={
    \ 'colorscheme': 'wombat',
    \ 'active': {
    \   'left': [['mode', 'paste'],
    \            ['gitbranch', 'readonly', 'filename', 'modified']]
    \ },
    \ 'component_function': {
    \   'gitbranch': 'fugitive#head'
    \ }
    \ }
let g:lightline.tabline={'left': [['buffers']], 'right': [['close']]}
let g:lightline.component_expand={'buffers': 'lightline#bufferline#buffers'}
let g:lightline.component_type={'buffers': 'tabsel'}

" vim-commentary
autocmd FileType markdown setlocal commentstring=<!--\ %s\ -->

" vim-clang-format
let g:clang_format#style_options={
    \ "Standard": "Cpp11",
    \ "BreakBeforeBraces": "Attach",
    \ "AccessModifierOffset": -4,
    \ "AllowShortIfStatementsOnASingleLine": "true"
    \ }
"autocmd FileType c,cpp,objc ClangFormatAutoEnable

" Colorizer
"let g:colorizer_auto_color = 1
"let g:colorizer_auto_filetype = 'css,html'
let g:colorizer_disable_bufleave = 1

" christoomey/vim-system-copy
let g:system_copy#copy_command='xclip -sel clipboard'
let g:system_copy#paste_command='xclip -sel clipboard -o'

" takac/vim-hardtime
let g:hardtime_default_on = 0
let g:list_of_normal_keys = []
let g:list_of_visual_keys = []
let g:list_of_insert_keys = []
let g:list_of_disabled_keys = ["<UP>", "<DOWN>", "<LEFT>", "<RIGHT>"]
let g:hardtime_timeout = 5000

" completor
if v:version >= 800
    let g:completor_clang_binary = '/usr/bin/clang'
    inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
    inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
    inoremap <expr> <cr> pumvisible() ? "\<C-y>\<cr>" : "\<cr>"
endif

" line numbers and color
set number
set relativenumber
set hlsearch
"colorscheme codedark
colorscheme gruvbox
set cursorline
set background=dark

" indentation
set tabstop=8
set softtabstop=0
set expandtab
set shiftwidth=4
set smarttab
set backspace=indent,eol,start
set tw=0

" highlight whitespace
set list
set listchars=
"set listchars+=eol:↲
set listchars+=tab:→\
set listchars+=trail:∙
set listchars+=extends:»
set listchars+=precedes:«
set listchars+=nbsp:⣿
set showbreak=↪\
"if has('patch-7.4.710')
"   set listchars+=space:𐄙
"endif

" search down into subfolders
" provides tab-completion for all file-related tasks
set path+=**

" display all matching files when tab completing
set wildmenu

" create the `tags` file
command! MakeTags !ctags -R .

" tweaks for file browsing
"let g:netrw_banner=0
"let g:netrw_browse_split=4
"let g:netrw_altv=1
"let g:netrw_liststyle=3
"let g:netrw_list_hide=netrw_gitignore#Hide()
"let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'
let g:netrw_fastbrowse=0

" nice to haves
"cnoremap w!! execute 'silent! write !sudo tee % > /dev/null' <bar> edit!
cnoremap w!! SudoWrite
fun! TrimWhitespace()
    let l:save = winsaveview()
    keeppatterns %s/\s\+$//e
    call winrestview(l:save)
endfun
command! TrimWhitespace call TrimWhitespace()
