---
# tasks file for roles/i3status

- name: Create i3status config directory
  become: yes
  become_user: "{{ user_id }}"
  file:
    path: "{{ user_config_dir }}/i3status"
    state: directory

- name: Generate i3status config files
  become: yes
  become_user: "{{ user_id }}"
  template:
    src: "{{ item }}.j2"
    dest: "{{ user_config_dir }}/i3status/{{ item }}"
    force: yes
  loop:
    - config
    - config-sm
