---
# tasks file for roles/i3status

- name: Create i3status config directory
  become: yes
  become_user: "{{ user_id }}"
  file:
    path: "{{ user_config_dir }}/i3status"
    state: directory

- name: Generate i3status config files
  become: yes
  become_user: "{{ user_id }}"
  template:
    src: "{{ item }}.j2"
    dest: "{{ user_config_dir }}/i3status/{{ item }}"
    force: yes
  loop:
    - config
    - config-sm

- name: Prepare i3status config files
  replace:
    path: "{{ user_config_dir }}/i3status/{{ item.0 }}"
    regexp: "{{ item.1.regexp }}"
    replace: "{{ item.1.replace }}"
  loop: "{{ configs | product(replaces) | list }}"
  vars:
    - configs:
      - config
      - config-sm
    - replaces:
      - { regexp: '({)', replace: '\1\1'  }
      - { regexp: '(})', replace: '\1\1'  }
      - { regexp: '@@(.+)@@', replace: '{\1}'  }
  when: theme_name == "wal"
