// Code generated by generator; DO NOT EDIT.
package profiles

import (
	enums "github.com/hanselrd/dotfiles/lib/enums"
	structs "github.com/hanselrd/dotfiles/lib/structs"
)

var MacOSBase = *structs.NewProfile(enums.SystemProfileMacOS, enums.UserProfileBase)
var MacOSStandard = *structs.NewProfile(enums.SystemProfileMacOS, enums.UserProfileStandard)
var MacOSMinimal = *structs.NewProfile(enums.SystemProfileMacOS, enums.UserProfileMinimal)
var MacOSFull = *structs.NewProfile(enums.SystemProfileMacOS, enums.UserProfileFull)
var DarwinProfiles = []structs.Profile{MacOSBase, MacOSStandard, MacOSMinimal, MacOSFull}
