// Code generated by generator; DO NOT EDIT.
package profiles

import (
	enums "github.com/hanselrd/dotfiles/lib/enums"
	structs "github.com/hanselrd/dotfiles/lib/structs"
)

var (
	LinuxBase     = *structs.NewProfile(enums.SystemProfileLinux, enums.UserProfileBase)
	LinuxStandard = *structs.NewProfile(enums.SystemProfileLinux, enums.UserProfileStandard)
	LinuxMinimal  = *structs.NewProfile(enums.SystemProfileLinux, enums.UserProfileMinimal)
	LinuxFull     = *structs.NewProfile(enums.SystemProfileLinux, enums.UserProfileFull)
)
var LinuxProfiles = []structs.Profile{LinuxBase, LinuxStandard, LinuxMinimal, LinuxFull}
