// Code generated by "generator"; DO NOT EDIT.
package profiles

import (
	"slices"

	enums "github.com/hanselrd/dotfiles/lib/enums"
	structs "github.com/hanselrd/dotfiles/lib/structs"
)

var (
	NixOSBase     = *structs.NewProfile(enums.SystemProfileNixOS, enums.UserProfileBase)
	NixOSStandard = *structs.NewProfile(enums.SystemProfileNixOS, enums.UserProfileStandard)
	NixOSMinimal  = *structs.NewProfile(enums.SystemProfileNixOS, enums.UserProfileMinimal)
	NixOSFull     = *structs.NewProfile(enums.SystemProfileNixOS, enums.UserProfileFull)
	MacOSBase     = *structs.NewProfile(enums.SystemProfileMacOS, enums.UserProfileBase)
	MacOSStandard = *structs.NewProfile(enums.SystemProfileMacOS, enums.UserProfileStandard)
	MacOSMinimal  = *structs.NewProfile(enums.SystemProfileMacOS, enums.UserProfileMinimal)
	MacOSFull     = *structs.NewProfile(enums.SystemProfileMacOS, enums.UserProfileFull)
	LinuxBase     = *structs.NewProfile(enums.SystemProfileLinux, enums.UserProfileBase)
	LinuxStandard = *structs.NewProfile(enums.SystemProfileLinux, enums.UserProfileStandard)
	LinuxMinimal  = *structs.NewProfile(enums.SystemProfileLinux, enums.UserProfileMinimal)
	LinuxFull     = *structs.NewProfile(enums.SystemProfileLinux, enums.UserProfileFull)
	WSLBase       = *structs.NewProfile(enums.SystemProfileWSL, enums.UserProfileBase)
	WSLStandard   = *structs.NewProfile(enums.SystemProfileWSL, enums.UserProfileStandard)
	WSLMinimal    = *structs.NewProfile(enums.SystemProfileWSL, enums.UserProfileMinimal)
	WSLFull       = *structs.NewProfile(enums.SystemProfileWSL, enums.UserProfileFull)
)

var (
	NixOSProfiles       = []structs.Profile{NixOSBase, NixOSStandard, NixOSMinimal, NixOSFull}
	MacOSProfiles       = []structs.Profile{MacOSBase, MacOSStandard, MacOSMinimal, MacOSFull}
	LinuxProfiles       = []structs.Profile{LinuxBase, LinuxStandard, LinuxMinimal, LinuxFull}
	WSLProfiles         = []structs.Profile{WSLBase, WSLStandard, WSLMinimal, WSLFull}
	HomeManagerProfiles = slices.Concat(NixOSProfiles, MacOSProfiles, LinuxProfiles, WSLProfiles)
)
