// Code generated by generator; DO NOT EDIT.
package profiles

import (
	enums "github.com/hanselrd/dotfiles/lib/enums"
	structs "github.com/hanselrd/dotfiles/lib/structs"
)

var WSLBase = *structs.NewProfile(enums.SystemProfileWSL, enums.UserProfileBase)
var WSLStandard = *structs.NewProfile(enums.SystemProfileWSL, enums.UserProfileStandard)
var WSLMinimal = *structs.NewProfile(enums.SystemProfileWSL, enums.UserProfileMinimal)
var WSLFull = *structs.NewProfile(enums.SystemProfileWSL, enums.UserProfileFull)
var WSLProfiles = []structs.Profile{WSLBase, WSLStandard, WSLMinimal, WSLFull}
