// Code generated by generator; DO NOT EDIT.
package profiles

import (
	enums "github.com/hanselrd/dotfiles/lib/enums"
	structs "github.com/hanselrd/dotfiles/lib/structs"
)

var (
	WSLBase     = *structs.NewProfile(enums.SystemProfileWSL, enums.UserProfileBase)
	WSLStandard = *structs.NewProfile(enums.SystemProfileWSL, enums.UserProfileStandard)
	WSLMinimal  = *structs.NewProfile(enums.SystemProfileWSL, enums.UserProfileMinimal)
	WSLFull     = *structs.NewProfile(enums.SystemProfileWSL, enums.UserProfileFull)
)
var WSLProfiles = []structs.Profile{WSLBase, WSLStandard, WSLMinimal, WSLFull}
