#!/usr/bin/env sh

cd "$(dirname "$0")" || exit

# $1 = {{ dotfiles_configuration }}
case "$1" in
    laptop|work)
        case "$2" in
            start|restart)
                case "$1" in
                    laptop)
                        ./df_launcher redshift -P -t 5500:2500 -l 40.7128:-74.0060
                        ;;
                    work)
                        ./df_launcher redshift -P -O 3500
                        ;;
                esac
                ;;
            stop)
                redshift -x
                killall -q redshift
                ;;
            *)
                echo "Usage: $0 {{ dotfiles_configuration }} {start|restart|stop}"
                echo "$2 not supported"
                exit 2
                ;;
        esac
        ;;
    *)
        echo "Usage: $0 {{ dotfiles_configuration }} {start|restart|stop}"
        echo "$1 not supported"
        exit 1
        ;;
esac
