#!/usr/bin/env sh

# cd "$(dirname "$0")" || exit

archive_basename=$(date +"%Y%m%d%H%M%N_$(neofetch model | cut -d ' ' -f 2- | sed 's/ *$//g' | tr ' ' _ | tr '[:lower:]' '[:upper:]')")

case "$1" in
    home|root)
        case "$1" in
            home)
                "$HOME/.scripts/df_archive encrypt" "$(printf "%s_HOME_%s_BACKUP.tar.gz" "$archive_basename" "$USER")" "$HOME/Desktop" "$HOME/Documents" "$HOME/Downloads" "$HOME/Music" "$HOME/Pictures" "$HOME/Public" "$HOME/Templates" "$HOME/Videos"
                ;;
            root)
                "/home/$SUDO_USER/.scripts/df_archive encrypt" "$(printf "%s_ROOT_%s_BACKUP.tar.gz" "$archive_basename" "$SUDO_USER")" /etc
                ;;
        esac
        ;;
    *)
        echo "Usage: $0 {home|root}"
        echo "$1 not supported"
        exit 1
        ;;
esac
