---
# tasks file for roles/ssh

- name: Create ssh directory
  become: yes
  become_user: "{{ user_id }}"
  file:
    path: "{{ user_home_dir }}/.ssh"
    state: directory

- name: Generate ssh keypair
  become: yes
  become_user: "{{ user_id }}"
  openssh_keypair:
    path: "{{ user_home_dir }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present

- name: Copy ssh config files
  become: yes
  become_user: "{{ user_id }}"
  copy:
    src: "{{ item }}"
    dest: "{{ user_home_dir }}/.ssh/{{ item }}"
    force: yes
  loop:
    - config
