// Code generated by "marshaler -type Encryption -stringer NixString"; DO NOT EDIT.
package encryption

import "encoding/json"

// MarshalJSON implements the json.Marshaler interface for Encryption
func (i Encryption) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.NixString())
}

// MarshalText implements the encoding.TextMarshaler interface for Encryption
func (i Encryption) MarshalText() ([]byte, error) {
	return []byte(i.NixString()), nil
}
