//go:build ignore

package main

import (
	"fmt"
	"os"
	"path/filepath"

	. "github.com/dave/jennifer/jen"
)

func main() {
	goPackage := os.Getenv("GOPACKAGE")

	f := NewFile(goPackage)

	f.PackageComment("Code generated by generator; DO NOT EDIT.")

	f.Var().Id("Reflect").
		Op("=").Map(String()).
		Interface().
		Values(
			DictFunc(func(d Dict) {
				for _, t := range os.Args[1:] {
					d[Lit(fmt.Sprintf("%ss", t))] = Id(fmt.Sprintf("%ss", t))
				}
			}))

	goFile := os.Getenv("GOFILE")
	ext := filepath.Ext(goFile)
	baseFilename := goFile[0 : len(goFile)-len(ext)]
	targetFilename := baseFilename + "_gen.go"

	f.Save(targetFilename)
}
