// Code generated by generator; DO NOT EDIT.
package enums

var Reflect = map[string]interface{}{
	"SystemProfiles": SystemProfiles,
	"SystemRoles":    SystemRoles,
	"Themes":         Themes,
	"UserProfiles":   UserProfiles,
	"UserRoles":      UserRoles,
}
