// Code generated by generator; DO NOT EDIT.
package enums

var Reflect = map[string]interface{}{
	"Roles":          Roles,
	"SystemProfiles": SystemProfiles,
	"Themes":         Themes,
	"UserProfiles":   UserProfiles,
}
