// Code generated by generator; DO NOT EDIT.
package enums

import "encoding/json"

func Roles() []Role {
	m := make([]Role, len(_Role_index)-1)
	for i := range _Role_index[:len(_Role_index)-1] {
		m[i] = Role(i)
	}
	return m
}
func (i Role) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}
func (i Role) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}
