// Code generated by "stringer -type Role -linecomment"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RoleBrowser-0]
	_ = x[RoleCommon-1]
	_ = x[RoleDevelopment-2]
	_ = x[RoleDocker-3]
	_ = x[RoleEditor-4]
	_ = x[RoleHomeage-5]
	_ = x[RoleNix-6]
	_ = x[RoleOther-7]
	_ = x[RolePager-8]
	_ = x[RoleScripts-9]
	_ = x[RoleShell-10]
	_ = x[RoleTerminal-11]
	_ = x[RoleTheme-12]
}

const _Role_name = "browsercommondevelopmentdockereditorhomeagenixotherpagerscriptsshellterminaltheme"

var _Role_index = [...]uint8{0, 7, 13, 24, 30, 36, 43, 46, 51, 56, 63, 68, 76, 81}

func (i Role) String() string {
	if i >= Role(len(_Role_index)-1) {
		return "Role(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Role_name[_Role_index[i]:_Role_index[i+1]]
}
