// Code generated by "stringer -type SystemRole -linecomment"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SystemRoleBoot-0]
	_ = x[SystemRoleI18n-1]
	_ = x[SystemRoleMonitoring-2]
	_ = x[SystemRoleMotd-3]
	_ = x[SystemRoleNetworking-4]
	_ = x[SystemRoleNix-5]
	_ = x[SystemRoleShell-6]
	_ = x[SystemRoleTime-7]
	_ = x[SystemRoleUser-8]
	_ = x[SystemRoleVirtualization-9]
	_ = x[SystemRoleX11-10]
}

const _SystemRole_name = "booti18nmonitoringmotdnetworkingnixshelltimeuservirtualizationx11"

var _SystemRole_index = [...]uint8{0, 4, 8, 18, 22, 32, 35, 40, 44, 48, 62, 65}

func (i SystemRole) String() string {
	if i >= SystemRole(len(_SystemRole_index)-1) {
		return "SystemRole(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SystemRole_name[_SystemRole_index[i]:_SystemRole_index[i+1]]
}
