// Code generated by generator; DO NOT EDIT.
package enums

import "encoding/json"

func SystemRoles() []SystemRole {
	m := make([]SystemRole, len(_SystemRole_index)-1)
	for i := range _SystemRole_index[:len(_SystemRole_index)-1] {
		m[i] = SystemRole(i)
	}
	return m
}
func (i SystemRole) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}
func (i SystemRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}
