// Code generated by "stringer -type SystemProfile -linecomment"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SystemProfileNixOS-0]
	_ = x[SystemProfileMacOS-1]
	_ = x[SystemProfileLinuxSystemd-2]
	_ = x[SystemProfileLinux-3]
	_ = x[SystemProfileWSL-4]
}

const _SystemProfile_name = "nixosmacoslinux-systemdlinuxwsl"

var _SystemProfile_index = [...]uint8{0, 5, 10, 23, 28, 31}

func (i SystemProfile) String() string {
	if i >= SystemProfile(len(_SystemProfile_index)-1) {
		return "SystemProfile(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SystemProfile_name[_SystemProfile_index[i]:_SystemProfile_index[i+1]]
}
