// Code generated by "enumer -type SystemProfile -trimprefix SystemProfile -linecomment -json -text"; DO NOT EDIT.

package enums

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _SystemProfileName = "NixOSMacOSLinuxWSL"

var _SystemProfileIndex = [...]uint8{0, 5, 10, 15, 18}

const _SystemProfileLowerName = "nixosmacoslinuxwsl"

func (i SystemProfile) String() string {
	if i >= SystemProfile(len(_SystemProfileIndex)-1) {
		return fmt.Sprintf("SystemProfile(%d)", i)
	}
	return _SystemProfileName[_SystemProfileIndex[i]:_SystemProfileIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SystemProfileNoOp() {
	var x [1]struct{}
	_ = x[SystemProfileNixOS-(0)]
	_ = x[SystemProfileMacOS-(1)]
	_ = x[SystemProfileLinux-(2)]
	_ = x[SystemProfileWSL-(3)]
}

var _SystemProfileValues = []SystemProfile{SystemProfileNixOS, SystemProfileMacOS, SystemProfileLinux, SystemProfileWSL}

var _SystemProfileNameToValueMap = map[string]SystemProfile{
	_SystemProfileName[0:5]:        SystemProfileNixOS,
	_SystemProfileLowerName[0:5]:   SystemProfileNixOS,
	_SystemProfileName[5:10]:       SystemProfileMacOS,
	_SystemProfileLowerName[5:10]:  SystemProfileMacOS,
	_SystemProfileName[10:15]:      SystemProfileLinux,
	_SystemProfileLowerName[10:15]: SystemProfileLinux,
	_SystemProfileName[15:18]:      SystemProfileWSL,
	_SystemProfileLowerName[15:18]: SystemProfileWSL,
}

var _SystemProfileNames = []string{
	_SystemProfileName[0:5],
	_SystemProfileName[5:10],
	_SystemProfileName[10:15],
	_SystemProfileName[15:18],
}

// SystemProfileString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SystemProfileString(s string) (SystemProfile, error) {
	if val, ok := _SystemProfileNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SystemProfileNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SystemProfile values", s)
}

// SystemProfileValues returns all values of the enum
func SystemProfileValues() []SystemProfile {
	return _SystemProfileValues
}

// SystemProfileStrings returns a slice of all String values of the enum
func SystemProfileStrings() []string {
	strs := make([]string, len(_SystemProfileNames))
	copy(strs, _SystemProfileNames)
	return strs
}

// IsASystemProfile returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SystemProfile) IsASystemProfile() bool {
	for _, v := range _SystemProfileValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SystemProfile
func (i SystemProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SystemProfile
func (i *SystemProfile) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SystemProfile should be a string, got %s", data)
	}

	var err error
	*i, err = SystemProfileString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for SystemProfile
func (i SystemProfile) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for SystemProfile
func (i *SystemProfile) UnmarshalText(text []byte) error {
	var err error
	*i, err = SystemProfileString(string(text))
	return err
}
