// Code generated by generator; DO NOT EDIT.
package enums

import "encoding/json"

func SystemProfiles() []SystemProfile {
	m := make([]SystemProfile, len(_SystemProfile_index)-1)
	for i := range _SystemProfile_index[:len(_SystemProfile_index)-1] {
		m[i] = SystemProfile(i)
	}
	return m
}
func (i SystemProfile) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}
func (i SystemProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}
