// Code generated by "stringer -type SystemRole -linecomment"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SystemRoleBootstrap-0]
	_ = x[SystemRoleBoot-1]
	_ = x[SystemRoleI18n-2]
	_ = x[SystemRoleKernel-3]
	_ = x[SystemRoleMonitoring-4]
	_ = x[SystemRoleMotd-5]
	_ = x[SystemRoleNetworking-6]
	_ = x[SystemRoleNix-7]
	_ = x[SystemRoleOpenSsh-8]
	_ = x[SystemRoleShell-9]
	_ = x[SystemRoleTime-10]
	_ = x[SystemRoleUser-11]
	_ = x[SystemRoleVirtualization-12]
	_ = x[SystemRoleX11-13]
}

const _SystemRole_name = "bootstrapbooti18nkernelmonitoringmotdnetworkingnixopensshshelltimeuservirtualizationx11"

var _SystemRole_index = [...]uint8{0, 9, 13, 17, 23, 33, 37, 47, 50, 57, 62, 66, 70, 84, 87}

func (i SystemRole) String() string {
	if i >= SystemRole(len(_SystemRole_index)-1) {
		return "SystemRole(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SystemRole_name[_SystemRole_index[i]:_SystemRole_index[i+1]]
}
