// Code generated by "stringer -type SystemProfile -linecomment"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SystemProfileNixos-0]
	_ = x[SystemProfileMacos-1]
	_ = x[SystemProfileLinux-2]
	_ = x[SystemProfileWsl-3]
}

const _SystemProfile_name = "nixosmacoslinuxwsl"

var _SystemProfile_index = [...]uint8{0, 5, 10, 15, 18}

func (i SystemProfile) String() string {
	if i >= SystemProfile(len(_SystemProfile_index)-1) {
		return "SystemProfile(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SystemProfile_name[_SystemProfile_index[i]:_SystemProfile_index[i+1]]
}
