// Code generated by generator; DO NOT EDIT.
package enums

import "encoding/json"

func Themes() []Theme {
	m := make([]Theme, len(_Theme_index)-1)
	for i := range _Theme_index[:len(_Theme_index)-1] {
		m[i] = Theme(i)
	}
	return m
}
func (i Theme) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}
func (i Theme) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}
