// Code generated by "stringer -type Theme -linecomment"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ThemeChalk-0]
	_ = x[ThemeGrayscale-1]
	_ = x[ThemeMatrix-2]
	_ = x[ThemeMocha-3]
	_ = x[ThemeOcean-4]
	_ = x[ThemeOneDark-5]
	_ = x[ThemeTomorrow-6]
	_ = x[ThemeTwilight-7]
}

const _Theme_name = "chalkgrayscalematrixmochaoceanone-darktomorrowtwilight"

var _Theme_index = [...]uint8{0, 5, 14, 20, 25, 30, 38, 46, 54}

func (i Theme) String() string {
	if i >= Theme(len(_Theme_index)-1) {
		return "Theme(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Theme_name[_Theme_index[i]:_Theme_index[i+1]]
}
