// Code generated by "stringer -type UserRole -linecomment"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserRoleBootstrap-0]
	_ = x[UserRoleAlacritty-1]
	_ = x[UserRoleBash-2]
	_ = x[UserRoleBat-3]
	_ = x[UserRoleBrowser-4]
	_ = x[UserRoleDevelopment-5]
	_ = x[UserRoleDevelopmentCpp-6]
	_ = x[UserRoleDevelopmentDhall-7]
	_ = x[UserRoleDevelopmentElixir-8]
	_ = x[UserRoleDevelopmentGo-9]
	_ = x[UserRoleDevelopmentHaskell-10]
	_ = x[UserRoleDevelopmentJava-11]
	_ = x[UserRoleDevelopmentKotlin-12]
	_ = x[UserRoleDevelopmentLua-13]
	_ = x[UserRoleDevelopmentNickel-14]
	_ = x[UserRoleDevelopmentNix-15]
	_ = x[UserRoleDevelopmentNodejs-16]
	_ = x[UserRoleDevelopmentPurescript-17]
	_ = x[UserRoleDevelopmentPython-18]
	_ = x[UserRoleDevelopmentRust-19]
	_ = x[UserRoleDevelopmentShell-20]
	_ = x[UserRoleDevelopmentZig-21]
	_ = x[UserRoleDocker-22]
	_ = x[UserRoleEditor-23]
	_ = x[UserRoleEza-24]
	_ = x[UserRoleFzf-25]
	_ = x[UserRoleGit-26]
	_ = x[UserRoleHomeage-27]
	_ = x[UserRoleHtop-28]
	_ = x[UserRoleNeovim-29]
	_ = x[UserRoleNix-30]
	_ = x[UserRolePager-31]
	_ = x[UserRoleRipgrep-32]
	_ = x[UserRoleScripts-33]
	_ = x[UserRoleShell-34]
	_ = x[UserRoleSsh-35]
	_ = x[UserRoleStarship-36]
	_ = x[UserRoleTerminal-37]
	_ = x[UserRoleTheme-38]
	_ = x[UserRoleTmux-39]
	_ = x[UserRoleVscode-40]
	_ = x[UserRoleZoxide-41]
	_ = x[UserRoleZsh-42]
	_ = x[UserRoleZzz-43]
}

const _UserRole_name = "bootstrapalacrittybashbatbrowserdevelopmentdevelopment.cppdevelopment.dhalldevelopment.elixirdevelopment.godevelopment.haskelldevelopment.javadevelopment.kotlindevelopment.luadevelopment.nickeldevelopment.nixdevelopment.nodejsdevelopment.purescriptdevelopment.pythondevelopment.rustdevelopment.shelldevelopment.zigdockereditorezafzfgithomeagehtopneovimnixpagerripgrepscriptsshellsshstarshipterminalthemetmuxvscodezoxidezshzzz"

var _UserRole_index = [...]uint16{0, 9, 18, 22, 25, 32, 43, 58, 75, 93, 107, 126, 142, 160, 175, 193, 208, 226, 248, 266, 282, 299, 314, 320, 326, 329, 332, 335, 342, 346, 352, 355, 360, 367, 374, 379, 382, 390, 398, 403, 407, 413, 419, 422, 425}

func (i UserRole) String() string {
	if i >= UserRole(len(_UserRole_index)-1) {
		return "UserRole(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserRole_name[_UserRole_index[i]:_UserRole_index[i+1]]
}
