// Code generated by "stringer -type UserRole -linecomment"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserRoleBrowser-0]
	_ = x[UserRoleDevelopment-1]
	_ = x[UserRoleDocker-2]
	_ = x[UserRoleEditor-3]
	_ = x[UserRoleHomeage-4]
	_ = x[UserRoleNix-5]
	_ = x[UserRolePager-6]
	_ = x[UserRoleShell-7]
	_ = x[UserRoleTerminal-8]
	_ = x[UserRoleTheme-9]
}

const _UserRole_name = "browserdevelopmentdockereditorhomeagenixpagershellterminaltheme"

var _UserRole_index = [...]uint8{0, 7, 18, 24, 30, 37, 40, 45, 50, 58, 63}

func (i UserRole) String() string {
	if i >= UserRole(len(_UserRole_index)-1) {
		return "UserRole(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserRole_name[_UserRole_index[i]:_UserRole_index[i+1]]
}
