// Code generated by generator; DO NOT EDIT.
package enums

import "encoding/json"

func UserProfiles() []UserProfile {
	m := make([]UserProfile, len(_UserProfile_index)-1)
	for i := range _UserProfile_index[:len(_UserProfile_index)-1] {
		m[i] = UserProfile(i)
	}
	return m
}
func (i UserProfile) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}
func (i UserProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}
