// Code generated by "stringer -type UserProfile -linecomment"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserProfileBase-0]
	_ = x[UserProfileStandard-1]
	_ = x[UserProfileMinimal-2]
	_ = x[UserProfileFull-3]
}

const _UserProfile_name = "basestandardminimalfull"

var _UserProfile_index = [...]uint8{0, 4, 12, 19, 23}

func (i UserProfile) String() string {
	if i >= UserProfile(len(_UserProfile_index)-1) {
		return "UserProfile(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserProfile_name[_UserProfile_index[i]:_UserProfile_index[i+1]]
}
