// Code generated by generator; DO NOT EDIT.
package enums

import "encoding/json"

func UserRoles() []UserRole {
	m := make([]UserRole, len(_UserRole_index)-1)
	for i := range _UserRole_index[:len(_UserRole_index)-1] {
		m[i] = UserRole(i)
	}
	return m
}
func (i UserRole) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}
func (i UserRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}
