// Code generated by "generator"; DO NOT EDIT.
package environment

type environmentRoles struct {
	System *environmentRolesSystem `json:"system,omitempty"`
	User   *environmentRolesUser   `json:"user,omitempty"`
}
type environmentRolesSystem struct {
	Bootstrap   *environmentRolesSystemBootstrap   `json:"bootstrap,omitempty"`
	Boot        *environmentRolesSystemBoot        `json:"boot,omitempty"`
	Cockpit     *environmentRolesSystemCockpit     `json:"cockpit,omitempty"`
	Docker      *environmentRolesSystemDocker      `json:"docker,omitempty"`
	Garuda      *environmentRolesSystemGaruda      `json:"garuda,omitempty"`
	HomeManager *environmentRolesSystemHomeManager `json:"home-manager,omitempty"`
	Hyprland    *environmentRolesSystemHyprland    `json:"hyprland,omitempty"`
	I18N        *environmentRolesSystemI18N        `json:"i18n,omitempty"`
	Kde         *environmentRolesSystemKde         `json:"kde,omitempty"`
	Kernel      *environmentRolesSystemKernel      `json:"kernel,omitempty"`
	Monitoring  *environmentRolesSystemMonitoring  `json:"monitoring,omitempty"`
	Motd        *environmentRolesSystemMotd        `json:"motd,omitempty"`
	Networking  *environmentRolesSystemNetworking  `json:"networking,omitempty"`
	Nix         *environmentRolesSystemNix         `json:"nix,omitempty"`
	Openssh     *environmentRolesSystemOpenssh     `json:"openssh,omitempty"`
	Shell       *environmentRolesSystemShell       `json:"shell,omitempty"`
	Sudo        *environmentRolesSystemSudo        `json:"sudo,omitempty"`
	Time        *environmentRolesSystemTime        `json:"time,omitempty"`
	Udisks2     *environmentRolesSystemUdisks2     `json:"udisks2,omitempty"`
	User        *environmentRolesSystemUser        `json:"user,omitempty"`
	Wsl         *environmentRolesSystemWsl         `json:"wsl,omitempty"`
	Xserver     *environmentRolesSystemXserver     `json:"xserver,omitempty"`
	Xrdp        *environmentRolesSystemXrdp        `json:"xrdp,omitempty"`
}
type environmentRolesUser struct {
	Bootstrap             *environmentRolesUserBootstrap             `json:"bootstrap,omitempty"`
	Alacritty             *environmentRolesUserAlacritty             `json:"alacritty,omitempty"`
	Bash                  *environmentRolesUserBash                  `json:"bash,omitempty"`
	Bat                   *environmentRolesUserBat                   `json:"bat,omitempty"`
	Brave                 *environmentRolesUserBrave                 `json:"brave,omitempty"`
	Browser               *environmentRolesUserBrowser               `json:"browser,omitempty"`
	Btop                  *environmentRolesUserBtop                  `json:"btop,omitempty"`
	Development           *environmentRolesUserDevelopment           `json:"development,omitempty"`
	DevelopmentCpp        *environmentRolesUserDevelopmentCpp        `json:"development.cpp,omitempty"`
	DevelopmentDhall      *environmentRolesUserDevelopmentDhall      `json:"development.dhall,omitempty"`
	DevelopmentElixir     *environmentRolesUserDevelopmentElixir     `json:"development.elixir,omitempty"`
	DevelopmentGleam      *environmentRolesUserDevelopmentGleam      `json:"development.gleam,omitempty"`
	DevelopmentGo         *environmentRolesUserDevelopmentGo         `json:"development.go,omitempty"`
	DevelopmentHaskell    *environmentRolesUserDevelopmentHaskell    `json:"development.haskell,omitempty"`
	DevelopmentJava       *environmentRolesUserDevelopmentJava       `json:"development.java,omitempty"`
	DevelopmentKotlin     *environmentRolesUserDevelopmentKotlin     `json:"development.kotlin,omitempty"`
	DevelopmentLua        *environmentRolesUserDevelopmentLua        `json:"development.lua,omitempty"`
	DevelopmentNickel     *environmentRolesUserDevelopmentNickel     `json:"development.nickel,omitempty"`
	DevelopmentNix        *environmentRolesUserDevelopmentNix        `json:"development.nix,omitempty"`
	DevelopmentNodejs     *environmentRolesUserDevelopmentNodejs     `json:"development.nodejs,omitempty"`
	DevelopmentPurescript *environmentRolesUserDevelopmentPurescript `json:"development.purescript,omitempty"`
	DevelopmentPython     *environmentRolesUserDevelopmentPython     `json:"development.python,omitempty"`
	DevelopmentRust       *environmentRolesUserDevelopmentRust       `json:"development.rust,omitempty"`
	DevelopmentShell      *environmentRolesUserDevelopmentShell      `json:"development.shell,omitempty"`
	DevelopmentZig        *environmentRolesUserDevelopmentZig        `json:"development.zig,omitempty"`
	Docker                *environmentRolesUserDocker                `json:"docker,omitempty"`
	Editor                *environmentRolesUserEditor                `json:"editor,omitempty"`
	Eza                   *environmentRolesUserEza                   `json:"eza,omitempty"`
	Fastfetch             *environmentRolesUserFastfetch             `json:"fastfetch,omitempty"`
	Flameshot             *environmentRolesUserFlameshot             `json:"flameshot,omitempty"`
	Fonts                 *environmentRolesUserFonts                 `json:"fonts,omitempty"`
	Fzf                   *environmentRolesUserFzf                   `json:"fzf,omitempty"`
	Gdb                   *environmentRolesUserGdb                   `json:"gdb,omitempty"`
	Git                   *environmentRolesUserGit                   `json:"git,omitempty"`
	Htop                  *environmentRolesUserHtop                  `json:"htop,omitempty"`
	Neovim                *environmentRolesUserNeovim                `json:"neovim,omitempty"`
	Nix                   *environmentRolesUserNix                   `json:"nix,omitempty"`
	OhMyPosh              *environmentRolesUserOhMyPosh              `json:"oh-my-posh,omitempty"`
	Pager                 *environmentRolesUserPager                 `json:"pager,omitempty"`
	Ranger                *environmentRolesUserRanger                `json:"ranger,omitempty"`
	Redshift              *environmentRolesUserRedshift              `json:"redshift,omitempty"`
	Ripgrep               *environmentRolesUserRipgrep               `json:"ripgrep,omitempty"`
	Rofi                  *environmentRolesUserRofi                  `json:"rofi,omitempty"`
	Rts                   *environmentRolesUserRts                   `json:"rts,omitempty"`
	Scripts               *environmentRolesUserScripts               `json:"scripts,omitempty"`
	Shell                 *environmentRolesUserShell                 `json:"shell,omitempty"`
	Ssh                   *environmentRolesUserSsh                   `json:"ssh,omitempty"`
	Starship              *environmentRolesUserStarship              `json:"starship,omitempty"`
	Sxhkd                 *environmentRolesUserSxhkd                 `json:"sxhkd,omitempty"`
	Terminal              *environmentRolesUserTerminal              `json:"terminal,omitempty"`
	Theme                 *environmentRolesUserTheme                 `json:"theme,omitempty"`
	Tmux                  *environmentRolesUserTmux                  `json:"tmux,omitempty"`
	Vscode                *environmentRolesUserVscode                `json:"vscode,omitempty"`
	Xdg                   *environmentRolesUserXdg                   `json:"xdg,omitempty"`
	Zoxide                *environmentRolesUserZoxide                `json:"zoxide,omitempty"`
	Zsh                   *environmentRolesUserZsh                   `json:"zsh,omitempty"`
}
