//go:build ignore

package main

import (
	"fmt"
	"os"
	"path/filepath"

	. "github.com/dave/jennifer/jen"

	"github.com/hanselrd/dotfiles/pkg/role"
)

func main() {
	goPackage := os.Getenv("GOPACKAGE")

	f := NewFile(goPackage)

	f.PackageComment("Code generated by \"generator\"; DO NOT EDIT.")

	// TODO: update to use PrivilegeLevel
	f.Type().Id("environmentRoles").Struct(
		Id("System").Op("*").
			Id("environmentRolesSystem").
			Tag(map[string]string{"json": "system,omitempty"}),
		Id("User").Op("*").
			Id("environmentRolesUser").
			Tag(map[string]string{"json": "user,omitempty"}),
	)

	f.Type().Id("environmentRolesSystem").StructFunc(func(g *Group) {
		for _, systemRole := range role.SystemRoleValues() {
			g.Id(systemRole.String()).
				Op("*").
				Id(fmt.Sprintf("environmentRolesSystem%s", systemRole)).
				Tag(map[string]string{"json": fmt.Sprintf("%s,omitempty", systemRole.NixString())})
		}
	})

	f.Type().Id("environmentRolesUser").StructFunc(func(g *Group) {
		for _, userRole := range role.UserRoleValues() {
			g.Id(userRole.String()).
				Op("*").
				Id(fmt.Sprintf("environmentRolesUser%s", userRole)).
				Tag(map[string]string{"json": fmt.Sprintf("%s,omitempty", userRole.NixString())})
		}
	})

	goFile := os.Getenv("GOFILE")
	ext := filepath.Ext(goFile)
	baseFilename := goFile[0 : len(goFile)-len(ext)]
	targetFilename := baseFilename + "_gen.go"

	f.Save(targetFilename)
}
