// Code generated by "privilegelevelfuncmap Role"; DO NOT EDIT.
package role

import (
	"reflect"

	lo "github.com/samber/lo"

	privilegelevel "github.com/hanselrd/dotfiles/internal/privilegelevel"
)

var RolePrivilegeLevelFuncMap = rolePrivilegeLevelFuncMap{
	privilegelevel.PrivilegeLevelSystem: {
		"String":  SystemRoleString,
		"Strings": SystemRoleStrings,
		"Values":  SystemRoleValues,
	},
	privilegelevel.PrivilegeLevelUser: {
		"String":  UserRoleString,
		"Strings": UserRoleStrings,
		"Values":  UserRoleValues,
	},
}

type rolePrivilegeLevelFuncMap map[privilegelevel.PrivilegeLevel]map[string]any

func (m rolePrivilegeLevelFuncMap) String(pl privilegelevel.PrivilegeLevel, s string) (Role, error) {
	res := reflect.ValueOf(m[pl]["String"]).Call([]reflect.Value{reflect.ValueOf(s)})
	if err, ok := res[1].Interface().(error); ok {
		return nil, err
	}
	return res[0].Interface().(Role), nil
}

func (m rolePrivilegeLevelFuncMap) Values(pl privilegelevel.PrivilegeLevel) []Role {
	res := reflect.ValueOf(m[pl]["Values"]).Call([]reflect.Value{})
	return lo.RepeatBy(res[0].Len(), func(i int) Role {
		return res[0].Index(i).Interface().(Role)
	})
}

func (m rolePrivilegeLevelFuncMap) Strings(pl privilegelevel.PrivilegeLevel) []string {
	res := reflect.ValueOf(m[pl]["Strings"]).Call([]reflect.Value{})
	return res[0].Interface().([]string)
}
