// Code generated by "enumer -type SystemRole -trimprefix SystemRole -linecomment -json -text -transform lower"; DO NOT EDIT.

package role

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _SystemRoleName = "bootstrapbootcockpitdockergarudahome-manageri18nkdekernelmonitoringmotdnetworkingnixopensshshellsudotimeuserwslxserverxrdp"

var _SystemRoleIndex = [...]uint8{0, 9, 13, 20, 26, 32, 44, 48, 51, 57, 67, 71, 81, 84, 91, 96, 100, 104, 108, 111, 118, 122}

const _SystemRoleLowerName = "bootstrapbootcockpitdockergarudahome-manageri18nkdekernelmonitoringmotdnetworkingnixopensshshellsudotimeuserwslxserverxrdp"

func (i SystemRole) String() string {
	if i >= SystemRole(len(_SystemRoleIndex)-1) {
		return fmt.Sprintf("SystemRole(%d)", i)
	}
	return _SystemRoleName[_SystemRoleIndex[i]:_SystemRoleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SystemRoleNoOp() {
	var x [1]struct{}
	_ = x[SystemRoleBootstrap-(0)]
	_ = x[SystemRoleBoot-(1)]
	_ = x[SystemRoleCockpit-(2)]
	_ = x[SystemRoleDocker-(3)]
	_ = x[SystemRoleGaruda-(4)]
	_ = x[SystemRoleHomeManager-(5)]
	_ = x[SystemRoleI18N-(6)]
	_ = x[SystemRoleKDE-(7)]
	_ = x[SystemRoleKernel-(8)]
	_ = x[SystemRoleMonitoring-(9)]
	_ = x[SystemRoleMotd-(10)]
	_ = x[SystemRoleNetworking-(11)]
	_ = x[SystemRoleNix-(12)]
	_ = x[SystemRoleOpenSsh-(13)]
	_ = x[SystemRoleShell-(14)]
	_ = x[SystemRoleSudo-(15)]
	_ = x[SystemRoleTime-(16)]
	_ = x[SystemRoleUser-(17)]
	_ = x[SystemRoleWsl-(18)]
	_ = x[SystemRoleXServer-(19)]
	_ = x[SystemRoleXrdp-(20)]
}

var _SystemRoleValues = []SystemRole{SystemRoleBootstrap, SystemRoleBoot, SystemRoleCockpit, SystemRoleDocker, SystemRoleGaruda, SystemRoleHomeManager, SystemRoleI18N, SystemRoleKDE, SystemRoleKernel, SystemRoleMonitoring, SystemRoleMotd, SystemRoleNetworking, SystemRoleNix, SystemRoleOpenSsh, SystemRoleShell, SystemRoleSudo, SystemRoleTime, SystemRoleUser, SystemRoleWsl, SystemRoleXServer, SystemRoleXrdp}

var _SystemRoleNameToValueMap = map[string]SystemRole{
	_SystemRoleName[0:9]:          SystemRoleBootstrap,
	_SystemRoleLowerName[0:9]:     SystemRoleBootstrap,
	_SystemRoleName[9:13]:         SystemRoleBoot,
	_SystemRoleLowerName[9:13]:    SystemRoleBoot,
	_SystemRoleName[13:20]:        SystemRoleCockpit,
	_SystemRoleLowerName[13:20]:   SystemRoleCockpit,
	_SystemRoleName[20:26]:        SystemRoleDocker,
	_SystemRoleLowerName[20:26]:   SystemRoleDocker,
	_SystemRoleName[26:32]:        SystemRoleGaruda,
	_SystemRoleLowerName[26:32]:   SystemRoleGaruda,
	_SystemRoleName[32:44]:        SystemRoleHomeManager,
	_SystemRoleLowerName[32:44]:   SystemRoleHomeManager,
	_SystemRoleName[44:48]:        SystemRoleI18N,
	_SystemRoleLowerName[44:48]:   SystemRoleI18N,
	_SystemRoleName[48:51]:        SystemRoleKDE,
	_SystemRoleLowerName[48:51]:   SystemRoleKDE,
	_SystemRoleName[51:57]:        SystemRoleKernel,
	_SystemRoleLowerName[51:57]:   SystemRoleKernel,
	_SystemRoleName[57:67]:        SystemRoleMonitoring,
	_SystemRoleLowerName[57:67]:   SystemRoleMonitoring,
	_SystemRoleName[67:71]:        SystemRoleMotd,
	_SystemRoleLowerName[67:71]:   SystemRoleMotd,
	_SystemRoleName[71:81]:        SystemRoleNetworking,
	_SystemRoleLowerName[71:81]:   SystemRoleNetworking,
	_SystemRoleName[81:84]:        SystemRoleNix,
	_SystemRoleLowerName[81:84]:   SystemRoleNix,
	_SystemRoleName[84:91]:        SystemRoleOpenSsh,
	_SystemRoleLowerName[84:91]:   SystemRoleOpenSsh,
	_SystemRoleName[91:96]:        SystemRoleShell,
	_SystemRoleLowerName[91:96]:   SystemRoleShell,
	_SystemRoleName[96:100]:       SystemRoleSudo,
	_SystemRoleLowerName[96:100]:  SystemRoleSudo,
	_SystemRoleName[100:104]:      SystemRoleTime,
	_SystemRoleLowerName[100:104]: SystemRoleTime,
	_SystemRoleName[104:108]:      SystemRoleUser,
	_SystemRoleLowerName[104:108]: SystemRoleUser,
	_SystemRoleName[108:111]:      SystemRoleWsl,
	_SystemRoleLowerName[108:111]: SystemRoleWsl,
	_SystemRoleName[111:118]:      SystemRoleXServer,
	_SystemRoleLowerName[111:118]: SystemRoleXServer,
	_SystemRoleName[118:122]:      SystemRoleXrdp,
	_SystemRoleLowerName[118:122]: SystemRoleXrdp,
}

var _SystemRoleNames = []string{
	_SystemRoleName[0:9],
	_SystemRoleName[9:13],
	_SystemRoleName[13:20],
	_SystemRoleName[20:26],
	_SystemRoleName[26:32],
	_SystemRoleName[32:44],
	_SystemRoleName[44:48],
	_SystemRoleName[48:51],
	_SystemRoleName[51:57],
	_SystemRoleName[57:67],
	_SystemRoleName[67:71],
	_SystemRoleName[71:81],
	_SystemRoleName[81:84],
	_SystemRoleName[84:91],
	_SystemRoleName[91:96],
	_SystemRoleName[96:100],
	_SystemRoleName[100:104],
	_SystemRoleName[104:108],
	_SystemRoleName[108:111],
	_SystemRoleName[111:118],
	_SystemRoleName[118:122],
}

// SystemRoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SystemRoleString(s string) (SystemRole, error) {
	if val, ok := _SystemRoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SystemRoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SystemRole values", s)
}

// SystemRoleValues returns all values of the enum
func SystemRoleValues() []SystemRole {
	return _SystemRoleValues
}

// SystemRoleStrings returns a slice of all String values of the enum
func SystemRoleStrings() []string {
	strs := make([]string, len(_SystemRoleNames))
	copy(strs, _SystemRoleNames)
	return strs
}

// IsASystemRole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SystemRole) IsASystemRole() bool {
	for _, v := range _SystemRoleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SystemRole
func (i SystemRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SystemRole
func (i *SystemRole) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SystemRole should be a string, got %s", data)
	}

	var err error
	*i, err = SystemRoleString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for SystemRole
func (i SystemRole) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for SystemRole
func (i *SystemRole) UnmarshalText(text []byte) error {
	var err error
	*i, err = SystemRoleString(string(text))
	return err
}
