// Code generated by "enumer -type UserRole -trimprefix UserRole -linecomment -json -text -transform lower"; DO NOT EDIT.

package role

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _UserRoleName = "bootstrapalacrittybashbatbravebrowserbtopdevelopmentdevelopment.cppdevelopment.dhalldevelopment.elixirdevelopment.gleamdevelopment.godevelopment.haskelldevelopment.javadevelopment.kotlindevelopment.luadevelopment.nickeldevelopment.nixdevelopment.nodejsdevelopment.purescriptdevelopment.pythondevelopment.rustdevelopment.shelldevelopment.zigdockereditorezaflameshotfontsfzfgdbgithtopneovimnixoh-my-poshpagerrangerredshiftripgreprofirtsscriptsshellsshstarshipsxhkdterminalthemetmuxvscodexdgzoxidezsh"

var _UserRoleIndex = [...]uint16{0, 9, 18, 22, 25, 30, 37, 41, 52, 67, 84, 102, 119, 133, 152, 168, 186, 201, 219, 234, 252, 274, 292, 308, 325, 340, 346, 352, 355, 364, 369, 372, 375, 378, 382, 388, 391, 401, 406, 412, 420, 427, 431, 434, 441, 446, 449, 457, 462, 470, 475, 479, 485, 488, 494, 497}

const _UserRoleLowerName = "bootstrapalacrittybashbatbravebrowserbtopdevelopmentdevelopment.cppdevelopment.dhalldevelopment.elixirdevelopment.gleamdevelopment.godevelopment.haskelldevelopment.javadevelopment.kotlindevelopment.luadevelopment.nickeldevelopment.nixdevelopment.nodejsdevelopment.purescriptdevelopment.pythondevelopment.rustdevelopment.shelldevelopment.zigdockereditorezaflameshotfontsfzfgdbgithtopneovimnixoh-my-poshpagerrangerredshiftripgreprofirtsscriptsshellsshstarshipsxhkdterminalthemetmuxvscodexdgzoxidezsh"

func (i UserRole) String() string {
	if i >= UserRole(len(_UserRoleIndex)-1) {
		return fmt.Sprintf("UserRole(%d)", i)
	}
	return _UserRoleName[_UserRoleIndex[i]:_UserRoleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _UserRoleNoOp() {
	var x [1]struct{}
	_ = x[UserRoleBootstrap-(0)]
	_ = x[UserRoleAlacritty-(1)]
	_ = x[UserRoleBash-(2)]
	_ = x[UserRoleBat-(3)]
	_ = x[UserRoleBrave-(4)]
	_ = x[UserRoleBrowser-(5)]
	_ = x[UserRoleBtop-(6)]
	_ = x[UserRoleDevelopment-(7)]
	_ = x[UserRoleDevelopmentCpp-(8)]
	_ = x[UserRoleDevelopmentDhall-(9)]
	_ = x[UserRoleDevelopmentElixir-(10)]
	_ = x[UserRoleDevelopmentGleam-(11)]
	_ = x[UserRoleDevelopmentGo-(12)]
	_ = x[UserRoleDevelopmentHaskell-(13)]
	_ = x[UserRoleDevelopmentJava-(14)]
	_ = x[UserRoleDevelopmentKotlin-(15)]
	_ = x[UserRoleDevelopmentLua-(16)]
	_ = x[UserRoleDevelopmentNickel-(17)]
	_ = x[UserRoleDevelopmentNix-(18)]
	_ = x[UserRoleDevelopmentNodejs-(19)]
	_ = x[UserRoleDevelopmentPurescript-(20)]
	_ = x[UserRoleDevelopmentPython-(21)]
	_ = x[UserRoleDevelopmentRust-(22)]
	_ = x[UserRoleDevelopmentShell-(23)]
	_ = x[UserRoleDevelopmentZig-(24)]
	_ = x[UserRoleDocker-(25)]
	_ = x[UserRoleEditor-(26)]
	_ = x[UserRoleEza-(27)]
	_ = x[UserRoleFlameshot-(28)]
	_ = x[UserRoleFonts-(29)]
	_ = x[UserRoleFzf-(30)]
	_ = x[UserRoleGdb-(31)]
	_ = x[UserRoleGit-(32)]
	_ = x[UserRoleHtop-(33)]
	_ = x[UserRoleNeovim-(34)]
	_ = x[UserRoleNix-(35)]
	_ = x[UserRoleOhMyPosh-(36)]
	_ = x[UserRolePager-(37)]
	_ = x[UserRoleRanger-(38)]
	_ = x[UserRoleRedshift-(39)]
	_ = x[UserRoleRipgrep-(40)]
	_ = x[UserRoleRofi-(41)]
	_ = x[UserRoleRts-(42)]
	_ = x[UserRoleScripts-(43)]
	_ = x[UserRoleShell-(44)]
	_ = x[UserRoleSsh-(45)]
	_ = x[UserRoleStarship-(46)]
	_ = x[UserRoleSxhkd-(47)]
	_ = x[UserRoleTerminal-(48)]
	_ = x[UserRoleTheme-(49)]
	_ = x[UserRoleTmux-(50)]
	_ = x[UserRoleVscode-(51)]
	_ = x[UserRoleXdg-(52)]
	_ = x[UserRoleZoxide-(53)]
	_ = x[UserRoleZsh-(54)]
}

var _UserRoleValues = []UserRole{UserRoleBootstrap, UserRoleAlacritty, UserRoleBash, UserRoleBat, UserRoleBrave, UserRoleBrowser, UserRoleBtop, UserRoleDevelopment, UserRoleDevelopmentCpp, UserRoleDevelopmentDhall, UserRoleDevelopmentElixir, UserRoleDevelopmentGleam, UserRoleDevelopmentGo, UserRoleDevelopmentHaskell, UserRoleDevelopmentJava, UserRoleDevelopmentKotlin, UserRoleDevelopmentLua, UserRoleDevelopmentNickel, UserRoleDevelopmentNix, UserRoleDevelopmentNodejs, UserRoleDevelopmentPurescript, UserRoleDevelopmentPython, UserRoleDevelopmentRust, UserRoleDevelopmentShell, UserRoleDevelopmentZig, UserRoleDocker, UserRoleEditor, UserRoleEza, UserRoleFlameshot, UserRoleFonts, UserRoleFzf, UserRoleGdb, UserRoleGit, UserRoleHtop, UserRoleNeovim, UserRoleNix, UserRoleOhMyPosh, UserRolePager, UserRoleRanger, UserRoleRedshift, UserRoleRipgrep, UserRoleRofi, UserRoleRts, UserRoleScripts, UserRoleShell, UserRoleSsh, UserRoleStarship, UserRoleSxhkd, UserRoleTerminal, UserRoleTheme, UserRoleTmux, UserRoleVscode, UserRoleXdg, UserRoleZoxide, UserRoleZsh}

var _UserRoleNameToValueMap = map[string]UserRole{
	_UserRoleName[0:9]:          UserRoleBootstrap,
	_UserRoleLowerName[0:9]:     UserRoleBootstrap,
	_UserRoleName[9:18]:         UserRoleAlacritty,
	_UserRoleLowerName[9:18]:    UserRoleAlacritty,
	_UserRoleName[18:22]:        UserRoleBash,
	_UserRoleLowerName[18:22]:   UserRoleBash,
	_UserRoleName[22:25]:        UserRoleBat,
	_UserRoleLowerName[22:25]:   UserRoleBat,
	_UserRoleName[25:30]:        UserRoleBrave,
	_UserRoleLowerName[25:30]:   UserRoleBrave,
	_UserRoleName[30:37]:        UserRoleBrowser,
	_UserRoleLowerName[30:37]:   UserRoleBrowser,
	_UserRoleName[37:41]:        UserRoleBtop,
	_UserRoleLowerName[37:41]:   UserRoleBtop,
	_UserRoleName[41:52]:        UserRoleDevelopment,
	_UserRoleLowerName[41:52]:   UserRoleDevelopment,
	_UserRoleName[52:67]:        UserRoleDevelopmentCpp,
	_UserRoleLowerName[52:67]:   UserRoleDevelopmentCpp,
	_UserRoleName[67:84]:        UserRoleDevelopmentDhall,
	_UserRoleLowerName[67:84]:   UserRoleDevelopmentDhall,
	_UserRoleName[84:102]:       UserRoleDevelopmentElixir,
	_UserRoleLowerName[84:102]:  UserRoleDevelopmentElixir,
	_UserRoleName[102:119]:      UserRoleDevelopmentGleam,
	_UserRoleLowerName[102:119]: UserRoleDevelopmentGleam,
	_UserRoleName[119:133]:      UserRoleDevelopmentGo,
	_UserRoleLowerName[119:133]: UserRoleDevelopmentGo,
	_UserRoleName[133:152]:      UserRoleDevelopmentHaskell,
	_UserRoleLowerName[133:152]: UserRoleDevelopmentHaskell,
	_UserRoleName[152:168]:      UserRoleDevelopmentJava,
	_UserRoleLowerName[152:168]: UserRoleDevelopmentJava,
	_UserRoleName[168:186]:      UserRoleDevelopmentKotlin,
	_UserRoleLowerName[168:186]: UserRoleDevelopmentKotlin,
	_UserRoleName[186:201]:      UserRoleDevelopmentLua,
	_UserRoleLowerName[186:201]: UserRoleDevelopmentLua,
	_UserRoleName[201:219]:      UserRoleDevelopmentNickel,
	_UserRoleLowerName[201:219]: UserRoleDevelopmentNickel,
	_UserRoleName[219:234]:      UserRoleDevelopmentNix,
	_UserRoleLowerName[219:234]: UserRoleDevelopmentNix,
	_UserRoleName[234:252]:      UserRoleDevelopmentNodejs,
	_UserRoleLowerName[234:252]: UserRoleDevelopmentNodejs,
	_UserRoleName[252:274]:      UserRoleDevelopmentPurescript,
	_UserRoleLowerName[252:274]: UserRoleDevelopmentPurescript,
	_UserRoleName[274:292]:      UserRoleDevelopmentPython,
	_UserRoleLowerName[274:292]: UserRoleDevelopmentPython,
	_UserRoleName[292:308]:      UserRoleDevelopmentRust,
	_UserRoleLowerName[292:308]: UserRoleDevelopmentRust,
	_UserRoleName[308:325]:      UserRoleDevelopmentShell,
	_UserRoleLowerName[308:325]: UserRoleDevelopmentShell,
	_UserRoleName[325:340]:      UserRoleDevelopmentZig,
	_UserRoleLowerName[325:340]: UserRoleDevelopmentZig,
	_UserRoleName[340:346]:      UserRoleDocker,
	_UserRoleLowerName[340:346]: UserRoleDocker,
	_UserRoleName[346:352]:      UserRoleEditor,
	_UserRoleLowerName[346:352]: UserRoleEditor,
	_UserRoleName[352:355]:      UserRoleEza,
	_UserRoleLowerName[352:355]: UserRoleEza,
	_UserRoleName[355:364]:      UserRoleFlameshot,
	_UserRoleLowerName[355:364]: UserRoleFlameshot,
	_UserRoleName[364:369]:      UserRoleFonts,
	_UserRoleLowerName[364:369]: UserRoleFonts,
	_UserRoleName[369:372]:      UserRoleFzf,
	_UserRoleLowerName[369:372]: UserRoleFzf,
	_UserRoleName[372:375]:      UserRoleGdb,
	_UserRoleLowerName[372:375]: UserRoleGdb,
	_UserRoleName[375:378]:      UserRoleGit,
	_UserRoleLowerName[375:378]: UserRoleGit,
	_UserRoleName[378:382]:      UserRoleHtop,
	_UserRoleLowerName[378:382]: UserRoleHtop,
	_UserRoleName[382:388]:      UserRoleNeovim,
	_UserRoleLowerName[382:388]: UserRoleNeovim,
	_UserRoleName[388:391]:      UserRoleNix,
	_UserRoleLowerName[388:391]: UserRoleNix,
	_UserRoleName[391:401]:      UserRoleOhMyPosh,
	_UserRoleLowerName[391:401]: UserRoleOhMyPosh,
	_UserRoleName[401:406]:      UserRolePager,
	_UserRoleLowerName[401:406]: UserRolePager,
	_UserRoleName[406:412]:      UserRoleRanger,
	_UserRoleLowerName[406:412]: UserRoleRanger,
	_UserRoleName[412:420]:      UserRoleRedshift,
	_UserRoleLowerName[412:420]: UserRoleRedshift,
	_UserRoleName[420:427]:      UserRoleRipgrep,
	_UserRoleLowerName[420:427]: UserRoleRipgrep,
	_UserRoleName[427:431]:      UserRoleRofi,
	_UserRoleLowerName[427:431]: UserRoleRofi,
	_UserRoleName[431:434]:      UserRoleRts,
	_UserRoleLowerName[431:434]: UserRoleRts,
	_UserRoleName[434:441]:      UserRoleScripts,
	_UserRoleLowerName[434:441]: UserRoleScripts,
	_UserRoleName[441:446]:      UserRoleShell,
	_UserRoleLowerName[441:446]: UserRoleShell,
	_UserRoleName[446:449]:      UserRoleSsh,
	_UserRoleLowerName[446:449]: UserRoleSsh,
	_UserRoleName[449:457]:      UserRoleStarship,
	_UserRoleLowerName[449:457]: UserRoleStarship,
	_UserRoleName[457:462]:      UserRoleSxhkd,
	_UserRoleLowerName[457:462]: UserRoleSxhkd,
	_UserRoleName[462:470]:      UserRoleTerminal,
	_UserRoleLowerName[462:470]: UserRoleTerminal,
	_UserRoleName[470:475]:      UserRoleTheme,
	_UserRoleLowerName[470:475]: UserRoleTheme,
	_UserRoleName[475:479]:      UserRoleTmux,
	_UserRoleLowerName[475:479]: UserRoleTmux,
	_UserRoleName[479:485]:      UserRoleVscode,
	_UserRoleLowerName[479:485]: UserRoleVscode,
	_UserRoleName[485:488]:      UserRoleXdg,
	_UserRoleLowerName[485:488]: UserRoleXdg,
	_UserRoleName[488:494]:      UserRoleZoxide,
	_UserRoleLowerName[488:494]: UserRoleZoxide,
	_UserRoleName[494:497]:      UserRoleZsh,
	_UserRoleLowerName[494:497]: UserRoleZsh,
}

var _UserRoleNames = []string{
	_UserRoleName[0:9],
	_UserRoleName[9:18],
	_UserRoleName[18:22],
	_UserRoleName[22:25],
	_UserRoleName[25:30],
	_UserRoleName[30:37],
	_UserRoleName[37:41],
	_UserRoleName[41:52],
	_UserRoleName[52:67],
	_UserRoleName[67:84],
	_UserRoleName[84:102],
	_UserRoleName[102:119],
	_UserRoleName[119:133],
	_UserRoleName[133:152],
	_UserRoleName[152:168],
	_UserRoleName[168:186],
	_UserRoleName[186:201],
	_UserRoleName[201:219],
	_UserRoleName[219:234],
	_UserRoleName[234:252],
	_UserRoleName[252:274],
	_UserRoleName[274:292],
	_UserRoleName[292:308],
	_UserRoleName[308:325],
	_UserRoleName[325:340],
	_UserRoleName[340:346],
	_UserRoleName[346:352],
	_UserRoleName[352:355],
	_UserRoleName[355:364],
	_UserRoleName[364:369],
	_UserRoleName[369:372],
	_UserRoleName[372:375],
	_UserRoleName[375:378],
	_UserRoleName[378:382],
	_UserRoleName[382:388],
	_UserRoleName[388:391],
	_UserRoleName[391:401],
	_UserRoleName[401:406],
	_UserRoleName[406:412],
	_UserRoleName[412:420],
	_UserRoleName[420:427],
	_UserRoleName[427:431],
	_UserRoleName[431:434],
	_UserRoleName[434:441],
	_UserRoleName[441:446],
	_UserRoleName[446:449],
	_UserRoleName[449:457],
	_UserRoleName[457:462],
	_UserRoleName[462:470],
	_UserRoleName[470:475],
	_UserRoleName[475:479],
	_UserRoleName[479:485],
	_UserRoleName[485:488],
	_UserRoleName[488:494],
	_UserRoleName[494:497],
}

// UserRoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func UserRoleString(s string) (UserRole, error) {
	if val, ok := _UserRoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _UserRoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to UserRole values", s)
}

// UserRoleValues returns all values of the enum
func UserRoleValues() []UserRole {
	return _UserRoleValues
}

// UserRoleStrings returns a slice of all String values of the enum
func UserRoleStrings() []string {
	strs := make([]string, len(_UserRoleNames))
	copy(strs, _UserRoleNames)
	return strs
}

// IsAUserRole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i UserRole) IsAUserRole() bool {
	for _, v := range _UserRoleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for UserRole
func (i UserRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for UserRole
func (i *UserRole) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("UserRole should be a string, got %s", data)
	}

	var err error
	*i, err = UserRoleString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for UserRole
func (i UserRole) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for UserRole
func (i *UserRole) UnmarshalText(text []byte) error {
	var err error
	*i, err = UserRoleString(string(text))
	return err
}
