// Code generated by "enumer -type UserRole -trimprefix UserRole"; DO NOT EDIT.

package role

import (
	"fmt"
	"strings"
)

const _UserRoleName = "BootstrapAlacrittyBashBatBinBottlesBraveBrowserBtopCMakeCcacheDevelopmentDevelopmentCppDevelopmentDhallDevelopmentElixirDevelopmentGleamDevelopmentGoDevelopmentHaskellDevelopmentJavaDevelopmentKotlinDevelopmentLuaDevelopmentNickelDevelopmentNixDevelopmentNodejsDevelopmentPurescriptDevelopmentPythonDevelopmentRustDevelopmentShellDevelopmentZigDockerEditorEzaFastfetchFlameshotFontsFzfGamingGdbGitHtopLldbMiscNeovimNixOhMyPoshPagerRangerRedshiftRipgrepRofiRtsShellSshStarshipSxhkdTerminalThemeTmuxVscodeWineWizTreeXdgZoxideZsh"

var _UserRoleIndex = [...]uint16{0, 9, 18, 22, 25, 28, 35, 40, 47, 51, 56, 62, 73, 87, 103, 120, 136, 149, 167, 182, 199, 213, 230, 244, 261, 282, 299, 314, 330, 344, 350, 356, 359, 368, 377, 382, 385, 391, 394, 397, 401, 405, 409, 415, 418, 426, 431, 437, 445, 452, 456, 459, 464, 467, 475, 480, 488, 493, 497, 503, 507, 514, 517, 523, 526}

const _UserRoleLowerName = "bootstrapalacrittybashbatbinbottlesbravebrowserbtopcmakeccachedevelopmentdevelopmentcppdevelopmentdhalldevelopmentelixirdevelopmentgleamdevelopmentgodevelopmenthaskelldevelopmentjavadevelopmentkotlindevelopmentluadevelopmentnickeldevelopmentnixdevelopmentnodejsdevelopmentpurescriptdevelopmentpythondevelopmentrustdevelopmentshelldevelopmentzigdockereditorezafastfetchflameshotfontsfzfgaminggdbgithtoplldbmiscneovimnixohmyposhpagerrangerredshiftripgreprofirtsshellsshstarshipsxhkdterminalthemetmuxvscodewinewiztreexdgzoxidezsh"

func (i UserRole) String() string {
	if i >= UserRole(len(_UserRoleIndex)-1) {
		return fmt.Sprintf("UserRole(%d)", i)
	}
	return _UserRoleName[_UserRoleIndex[i]:_UserRoleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _UserRoleNoOp() {
	var x [1]struct{}
	_ = x[UserRoleBootstrap-(0)]
	_ = x[UserRoleAlacritty-(1)]
	_ = x[UserRoleBash-(2)]
	_ = x[UserRoleBat-(3)]
	_ = x[UserRoleBin-(4)]
	_ = x[UserRoleBottles-(5)]
	_ = x[UserRoleBrave-(6)]
	_ = x[UserRoleBrowser-(7)]
	_ = x[UserRoleBtop-(8)]
	_ = x[UserRoleCMake-(9)]
	_ = x[UserRoleCcache-(10)]
	_ = x[UserRoleDevelopment-(11)]
	_ = x[UserRoleDevelopmentCpp-(12)]
	_ = x[UserRoleDevelopmentDhall-(13)]
	_ = x[UserRoleDevelopmentElixir-(14)]
	_ = x[UserRoleDevelopmentGleam-(15)]
	_ = x[UserRoleDevelopmentGo-(16)]
	_ = x[UserRoleDevelopmentHaskell-(17)]
	_ = x[UserRoleDevelopmentJava-(18)]
	_ = x[UserRoleDevelopmentKotlin-(19)]
	_ = x[UserRoleDevelopmentLua-(20)]
	_ = x[UserRoleDevelopmentNickel-(21)]
	_ = x[UserRoleDevelopmentNix-(22)]
	_ = x[UserRoleDevelopmentNodejs-(23)]
	_ = x[UserRoleDevelopmentPurescript-(24)]
	_ = x[UserRoleDevelopmentPython-(25)]
	_ = x[UserRoleDevelopmentRust-(26)]
	_ = x[UserRoleDevelopmentShell-(27)]
	_ = x[UserRoleDevelopmentZig-(28)]
	_ = x[UserRoleDocker-(29)]
	_ = x[UserRoleEditor-(30)]
	_ = x[UserRoleEza-(31)]
	_ = x[UserRoleFastfetch-(32)]
	_ = x[UserRoleFlameshot-(33)]
	_ = x[UserRoleFonts-(34)]
	_ = x[UserRoleFzf-(35)]
	_ = x[UserRoleGaming-(36)]
	_ = x[UserRoleGdb-(37)]
	_ = x[UserRoleGit-(38)]
	_ = x[UserRoleHtop-(39)]
	_ = x[UserRoleLldb-(40)]
	_ = x[UserRoleMisc-(41)]
	_ = x[UserRoleNeovim-(42)]
	_ = x[UserRoleNix-(43)]
	_ = x[UserRoleOhMyPosh-(44)]
	_ = x[UserRolePager-(45)]
	_ = x[UserRoleRanger-(46)]
	_ = x[UserRoleRedshift-(47)]
	_ = x[UserRoleRipgrep-(48)]
	_ = x[UserRoleRofi-(49)]
	_ = x[UserRoleRts-(50)]
	_ = x[UserRoleShell-(51)]
	_ = x[UserRoleSsh-(52)]
	_ = x[UserRoleStarship-(53)]
	_ = x[UserRoleSxhkd-(54)]
	_ = x[UserRoleTerminal-(55)]
	_ = x[UserRoleTheme-(56)]
	_ = x[UserRoleTmux-(57)]
	_ = x[UserRoleVscode-(58)]
	_ = x[UserRoleWine-(59)]
	_ = x[UserRoleWizTree-(60)]
	_ = x[UserRoleXdg-(61)]
	_ = x[UserRoleZoxide-(62)]
	_ = x[UserRoleZsh-(63)]
}

var _UserRoleValues = []UserRole{UserRoleBootstrap, UserRoleAlacritty, UserRoleBash, UserRoleBat, UserRoleBin, UserRoleBottles, UserRoleBrave, UserRoleBrowser, UserRoleBtop, UserRoleCMake, UserRoleCcache, UserRoleDevelopment, UserRoleDevelopmentCpp, UserRoleDevelopmentDhall, UserRoleDevelopmentElixir, UserRoleDevelopmentGleam, UserRoleDevelopmentGo, UserRoleDevelopmentHaskell, UserRoleDevelopmentJava, UserRoleDevelopmentKotlin, UserRoleDevelopmentLua, UserRoleDevelopmentNickel, UserRoleDevelopmentNix, UserRoleDevelopmentNodejs, UserRoleDevelopmentPurescript, UserRoleDevelopmentPython, UserRoleDevelopmentRust, UserRoleDevelopmentShell, UserRoleDevelopmentZig, UserRoleDocker, UserRoleEditor, UserRoleEza, UserRoleFastfetch, UserRoleFlameshot, UserRoleFonts, UserRoleFzf, UserRoleGaming, UserRoleGdb, UserRoleGit, UserRoleHtop, UserRoleLldb, UserRoleMisc, UserRoleNeovim, UserRoleNix, UserRoleOhMyPosh, UserRolePager, UserRoleRanger, UserRoleRedshift, UserRoleRipgrep, UserRoleRofi, UserRoleRts, UserRoleShell, UserRoleSsh, UserRoleStarship, UserRoleSxhkd, UserRoleTerminal, UserRoleTheme, UserRoleTmux, UserRoleVscode, UserRoleWine, UserRoleWizTree, UserRoleXdg, UserRoleZoxide, UserRoleZsh}

var _UserRoleNameToValueMap = map[string]UserRole{
	_UserRoleName[0:9]:          UserRoleBootstrap,
	_UserRoleLowerName[0:9]:     UserRoleBootstrap,
	_UserRoleName[9:18]:         UserRoleAlacritty,
	_UserRoleLowerName[9:18]:    UserRoleAlacritty,
	_UserRoleName[18:22]:        UserRoleBash,
	_UserRoleLowerName[18:22]:   UserRoleBash,
	_UserRoleName[22:25]:        UserRoleBat,
	_UserRoleLowerName[22:25]:   UserRoleBat,
	_UserRoleName[25:28]:        UserRoleBin,
	_UserRoleLowerName[25:28]:   UserRoleBin,
	_UserRoleName[28:35]:        UserRoleBottles,
	_UserRoleLowerName[28:35]:   UserRoleBottles,
	_UserRoleName[35:40]:        UserRoleBrave,
	_UserRoleLowerName[35:40]:   UserRoleBrave,
	_UserRoleName[40:47]:        UserRoleBrowser,
	_UserRoleLowerName[40:47]:   UserRoleBrowser,
	_UserRoleName[47:51]:        UserRoleBtop,
	_UserRoleLowerName[47:51]:   UserRoleBtop,
	_UserRoleName[51:56]:        UserRoleCMake,
	_UserRoleLowerName[51:56]:   UserRoleCMake,
	_UserRoleName[56:62]:        UserRoleCcache,
	_UserRoleLowerName[56:62]:   UserRoleCcache,
	_UserRoleName[62:73]:        UserRoleDevelopment,
	_UserRoleLowerName[62:73]:   UserRoleDevelopment,
	_UserRoleName[73:87]:        UserRoleDevelopmentCpp,
	_UserRoleLowerName[73:87]:   UserRoleDevelopmentCpp,
	_UserRoleName[87:103]:       UserRoleDevelopmentDhall,
	_UserRoleLowerName[87:103]:  UserRoleDevelopmentDhall,
	_UserRoleName[103:120]:      UserRoleDevelopmentElixir,
	_UserRoleLowerName[103:120]: UserRoleDevelopmentElixir,
	_UserRoleName[120:136]:      UserRoleDevelopmentGleam,
	_UserRoleLowerName[120:136]: UserRoleDevelopmentGleam,
	_UserRoleName[136:149]:      UserRoleDevelopmentGo,
	_UserRoleLowerName[136:149]: UserRoleDevelopmentGo,
	_UserRoleName[149:167]:      UserRoleDevelopmentHaskell,
	_UserRoleLowerName[149:167]: UserRoleDevelopmentHaskell,
	_UserRoleName[167:182]:      UserRoleDevelopmentJava,
	_UserRoleLowerName[167:182]: UserRoleDevelopmentJava,
	_UserRoleName[182:199]:      UserRoleDevelopmentKotlin,
	_UserRoleLowerName[182:199]: UserRoleDevelopmentKotlin,
	_UserRoleName[199:213]:      UserRoleDevelopmentLua,
	_UserRoleLowerName[199:213]: UserRoleDevelopmentLua,
	_UserRoleName[213:230]:      UserRoleDevelopmentNickel,
	_UserRoleLowerName[213:230]: UserRoleDevelopmentNickel,
	_UserRoleName[230:244]:      UserRoleDevelopmentNix,
	_UserRoleLowerName[230:244]: UserRoleDevelopmentNix,
	_UserRoleName[244:261]:      UserRoleDevelopmentNodejs,
	_UserRoleLowerName[244:261]: UserRoleDevelopmentNodejs,
	_UserRoleName[261:282]:      UserRoleDevelopmentPurescript,
	_UserRoleLowerName[261:282]: UserRoleDevelopmentPurescript,
	_UserRoleName[282:299]:      UserRoleDevelopmentPython,
	_UserRoleLowerName[282:299]: UserRoleDevelopmentPython,
	_UserRoleName[299:314]:      UserRoleDevelopmentRust,
	_UserRoleLowerName[299:314]: UserRoleDevelopmentRust,
	_UserRoleName[314:330]:      UserRoleDevelopmentShell,
	_UserRoleLowerName[314:330]: UserRoleDevelopmentShell,
	_UserRoleName[330:344]:      UserRoleDevelopmentZig,
	_UserRoleLowerName[330:344]: UserRoleDevelopmentZig,
	_UserRoleName[344:350]:      UserRoleDocker,
	_UserRoleLowerName[344:350]: UserRoleDocker,
	_UserRoleName[350:356]:      UserRoleEditor,
	_UserRoleLowerName[350:356]: UserRoleEditor,
	_UserRoleName[356:359]:      UserRoleEza,
	_UserRoleLowerName[356:359]: UserRoleEza,
	_UserRoleName[359:368]:      UserRoleFastfetch,
	_UserRoleLowerName[359:368]: UserRoleFastfetch,
	_UserRoleName[368:377]:      UserRoleFlameshot,
	_UserRoleLowerName[368:377]: UserRoleFlameshot,
	_UserRoleName[377:382]:      UserRoleFonts,
	_UserRoleLowerName[377:382]: UserRoleFonts,
	_UserRoleName[382:385]:      UserRoleFzf,
	_UserRoleLowerName[382:385]: UserRoleFzf,
	_UserRoleName[385:391]:      UserRoleGaming,
	_UserRoleLowerName[385:391]: UserRoleGaming,
	_UserRoleName[391:394]:      UserRoleGdb,
	_UserRoleLowerName[391:394]: UserRoleGdb,
	_UserRoleName[394:397]:      UserRoleGit,
	_UserRoleLowerName[394:397]: UserRoleGit,
	_UserRoleName[397:401]:      UserRoleHtop,
	_UserRoleLowerName[397:401]: UserRoleHtop,
	_UserRoleName[401:405]:      UserRoleLldb,
	_UserRoleLowerName[401:405]: UserRoleLldb,
	_UserRoleName[405:409]:      UserRoleMisc,
	_UserRoleLowerName[405:409]: UserRoleMisc,
	_UserRoleName[409:415]:      UserRoleNeovim,
	_UserRoleLowerName[409:415]: UserRoleNeovim,
	_UserRoleName[415:418]:      UserRoleNix,
	_UserRoleLowerName[415:418]: UserRoleNix,
	_UserRoleName[418:426]:      UserRoleOhMyPosh,
	_UserRoleLowerName[418:426]: UserRoleOhMyPosh,
	_UserRoleName[426:431]:      UserRolePager,
	_UserRoleLowerName[426:431]: UserRolePager,
	_UserRoleName[431:437]:      UserRoleRanger,
	_UserRoleLowerName[431:437]: UserRoleRanger,
	_UserRoleName[437:445]:      UserRoleRedshift,
	_UserRoleLowerName[437:445]: UserRoleRedshift,
	_UserRoleName[445:452]:      UserRoleRipgrep,
	_UserRoleLowerName[445:452]: UserRoleRipgrep,
	_UserRoleName[452:456]:      UserRoleRofi,
	_UserRoleLowerName[452:456]: UserRoleRofi,
	_UserRoleName[456:459]:      UserRoleRts,
	_UserRoleLowerName[456:459]: UserRoleRts,
	_UserRoleName[459:464]:      UserRoleShell,
	_UserRoleLowerName[459:464]: UserRoleShell,
	_UserRoleName[464:467]:      UserRoleSsh,
	_UserRoleLowerName[464:467]: UserRoleSsh,
	_UserRoleName[467:475]:      UserRoleStarship,
	_UserRoleLowerName[467:475]: UserRoleStarship,
	_UserRoleName[475:480]:      UserRoleSxhkd,
	_UserRoleLowerName[475:480]: UserRoleSxhkd,
	_UserRoleName[480:488]:      UserRoleTerminal,
	_UserRoleLowerName[480:488]: UserRoleTerminal,
	_UserRoleName[488:493]:      UserRoleTheme,
	_UserRoleLowerName[488:493]: UserRoleTheme,
	_UserRoleName[493:497]:      UserRoleTmux,
	_UserRoleLowerName[493:497]: UserRoleTmux,
	_UserRoleName[497:503]:      UserRoleVscode,
	_UserRoleLowerName[497:503]: UserRoleVscode,
	_UserRoleName[503:507]:      UserRoleWine,
	_UserRoleLowerName[503:507]: UserRoleWine,
	_UserRoleName[507:514]:      UserRoleWizTree,
	_UserRoleLowerName[507:514]: UserRoleWizTree,
	_UserRoleName[514:517]:      UserRoleXdg,
	_UserRoleLowerName[514:517]: UserRoleXdg,
	_UserRoleName[517:523]:      UserRoleZoxide,
	_UserRoleLowerName[517:523]: UserRoleZoxide,
	_UserRoleName[523:526]:      UserRoleZsh,
	_UserRoleLowerName[523:526]: UserRoleZsh,
}

var _UserRoleNames = []string{
	_UserRoleName[0:9],
	_UserRoleName[9:18],
	_UserRoleName[18:22],
	_UserRoleName[22:25],
	_UserRoleName[25:28],
	_UserRoleName[28:35],
	_UserRoleName[35:40],
	_UserRoleName[40:47],
	_UserRoleName[47:51],
	_UserRoleName[51:56],
	_UserRoleName[56:62],
	_UserRoleName[62:73],
	_UserRoleName[73:87],
	_UserRoleName[87:103],
	_UserRoleName[103:120],
	_UserRoleName[120:136],
	_UserRoleName[136:149],
	_UserRoleName[149:167],
	_UserRoleName[167:182],
	_UserRoleName[182:199],
	_UserRoleName[199:213],
	_UserRoleName[213:230],
	_UserRoleName[230:244],
	_UserRoleName[244:261],
	_UserRoleName[261:282],
	_UserRoleName[282:299],
	_UserRoleName[299:314],
	_UserRoleName[314:330],
	_UserRoleName[330:344],
	_UserRoleName[344:350],
	_UserRoleName[350:356],
	_UserRoleName[356:359],
	_UserRoleName[359:368],
	_UserRoleName[368:377],
	_UserRoleName[377:382],
	_UserRoleName[382:385],
	_UserRoleName[385:391],
	_UserRoleName[391:394],
	_UserRoleName[394:397],
	_UserRoleName[397:401],
	_UserRoleName[401:405],
	_UserRoleName[405:409],
	_UserRoleName[409:415],
	_UserRoleName[415:418],
	_UserRoleName[418:426],
	_UserRoleName[426:431],
	_UserRoleName[431:437],
	_UserRoleName[437:445],
	_UserRoleName[445:452],
	_UserRoleName[452:456],
	_UserRoleName[456:459],
	_UserRoleName[459:464],
	_UserRoleName[464:467],
	_UserRoleName[467:475],
	_UserRoleName[475:480],
	_UserRoleName[480:488],
	_UserRoleName[488:493],
	_UserRoleName[493:497],
	_UserRoleName[497:503],
	_UserRoleName[503:507],
	_UserRoleName[507:514],
	_UserRoleName[514:517],
	_UserRoleName[517:523],
	_UserRoleName[523:526],
}

// UserRoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func UserRoleString(s string) (UserRole, error) {
	if val, ok := _UserRoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _UserRoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to UserRole values", s)
}

// UserRoleValues returns all values of the enum
func UserRoleValues() []UserRole {
	return _UserRoleValues
}

// UserRoleStrings returns a slice of all String values of the enum
func UserRoleStrings() []string {
	strs := make([]string, len(_UserRoleNames))
	copy(strs, _UserRoleNames)
	return strs
}

// IsAUserRole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i UserRole) IsAUserRole() bool {
	for _, v := range _UserRoleValues {
		if i == v {
			return true
		}
	}
	return false
}
