// Code generated by "enumer -type UserRole -trimprefix UserRole -linecomment -json -text -transform lower"; DO NOT EDIT.

package role

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _UserRoleName = "bootstrapalacrittybashbatbravebrowserbtopdevelopmentdevelopment.cppdevelopment.dhalldevelopment.elixirdevelopment.gleamdevelopment.godevelopment.haskelldevelopment.javadevelopment.kotlindevelopment.luadevelopment.nickeldevelopment.nixdevelopment.nodejsdevelopment.purescriptdevelopment.pythondevelopment.rustdevelopment.shelldevelopment.zigdockereditorezafastfetchflameshotfontsfzfgdbgithtoplldbneovimnixoh-my-poshpagerrangerredshiftripgreprofirtsscriptsshellsshstarshipsxhkdterminalthemetmuxvscodexdgzoxidezsh"

var _UserRoleIndex = [...]uint16{0, 9, 18, 22, 25, 30, 37, 41, 52, 67, 84, 102, 119, 133, 152, 168, 186, 201, 219, 234, 252, 274, 292, 308, 325, 340, 346, 352, 355, 364, 373, 378, 381, 384, 387, 391, 395, 401, 404, 414, 419, 425, 433, 440, 444, 447, 454, 459, 462, 470, 475, 483, 488, 492, 498, 501, 507, 510}

const _UserRoleLowerName = "bootstrapalacrittybashbatbravebrowserbtopdevelopmentdevelopment.cppdevelopment.dhalldevelopment.elixirdevelopment.gleamdevelopment.godevelopment.haskelldevelopment.javadevelopment.kotlindevelopment.luadevelopment.nickeldevelopment.nixdevelopment.nodejsdevelopment.purescriptdevelopment.pythondevelopment.rustdevelopment.shelldevelopment.zigdockereditorezafastfetchflameshotfontsfzfgdbgithtoplldbneovimnixoh-my-poshpagerrangerredshiftripgreprofirtsscriptsshellsshstarshipsxhkdterminalthemetmuxvscodexdgzoxidezsh"

func (i UserRole) String() string {
	if i >= UserRole(len(_UserRoleIndex)-1) {
		return fmt.Sprintf("UserRole(%d)", i)
	}
	return _UserRoleName[_UserRoleIndex[i]:_UserRoleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _UserRoleNoOp() {
	var x [1]struct{}
	_ = x[UserRoleBootstrap-(0)]
	_ = x[UserRoleAlacritty-(1)]
	_ = x[UserRoleBash-(2)]
	_ = x[UserRoleBat-(3)]
	_ = x[UserRoleBrave-(4)]
	_ = x[UserRoleBrowser-(5)]
	_ = x[UserRoleBtop-(6)]
	_ = x[UserRoleDevelopment-(7)]
	_ = x[UserRoleDevelopmentCpp-(8)]
	_ = x[UserRoleDevelopmentDhall-(9)]
	_ = x[UserRoleDevelopmentElixir-(10)]
	_ = x[UserRoleDevelopmentGleam-(11)]
	_ = x[UserRoleDevelopmentGo-(12)]
	_ = x[UserRoleDevelopmentHaskell-(13)]
	_ = x[UserRoleDevelopmentJava-(14)]
	_ = x[UserRoleDevelopmentKotlin-(15)]
	_ = x[UserRoleDevelopmentLua-(16)]
	_ = x[UserRoleDevelopmentNickel-(17)]
	_ = x[UserRoleDevelopmentNix-(18)]
	_ = x[UserRoleDevelopmentNodejs-(19)]
	_ = x[UserRoleDevelopmentPurescript-(20)]
	_ = x[UserRoleDevelopmentPython-(21)]
	_ = x[UserRoleDevelopmentRust-(22)]
	_ = x[UserRoleDevelopmentShell-(23)]
	_ = x[UserRoleDevelopmentZig-(24)]
	_ = x[UserRoleDocker-(25)]
	_ = x[UserRoleEditor-(26)]
	_ = x[UserRoleEza-(27)]
	_ = x[UserRoleFastfetch-(28)]
	_ = x[UserRoleFlameshot-(29)]
	_ = x[UserRoleFonts-(30)]
	_ = x[UserRoleFzf-(31)]
	_ = x[UserRoleGdb-(32)]
	_ = x[UserRoleGit-(33)]
	_ = x[UserRoleHtop-(34)]
	_ = x[UserRoleLldb-(35)]
	_ = x[UserRoleNeovim-(36)]
	_ = x[UserRoleNix-(37)]
	_ = x[UserRoleOhMyPosh-(38)]
	_ = x[UserRolePager-(39)]
	_ = x[UserRoleRanger-(40)]
	_ = x[UserRoleRedshift-(41)]
	_ = x[UserRoleRipgrep-(42)]
	_ = x[UserRoleRofi-(43)]
	_ = x[UserRoleRts-(44)]
	_ = x[UserRoleScripts-(45)]
	_ = x[UserRoleShell-(46)]
	_ = x[UserRoleSsh-(47)]
	_ = x[UserRoleStarship-(48)]
	_ = x[UserRoleSxhkd-(49)]
	_ = x[UserRoleTerminal-(50)]
	_ = x[UserRoleTheme-(51)]
	_ = x[UserRoleTmux-(52)]
	_ = x[UserRoleVscode-(53)]
	_ = x[UserRoleXdg-(54)]
	_ = x[UserRoleZoxide-(55)]
	_ = x[UserRoleZsh-(56)]
}

var _UserRoleValues = []UserRole{UserRoleBootstrap, UserRoleAlacritty, UserRoleBash, UserRoleBat, UserRoleBrave, UserRoleBrowser, UserRoleBtop, UserRoleDevelopment, UserRoleDevelopmentCpp, UserRoleDevelopmentDhall, UserRoleDevelopmentElixir, UserRoleDevelopmentGleam, UserRoleDevelopmentGo, UserRoleDevelopmentHaskell, UserRoleDevelopmentJava, UserRoleDevelopmentKotlin, UserRoleDevelopmentLua, UserRoleDevelopmentNickel, UserRoleDevelopmentNix, UserRoleDevelopmentNodejs, UserRoleDevelopmentPurescript, UserRoleDevelopmentPython, UserRoleDevelopmentRust, UserRoleDevelopmentShell, UserRoleDevelopmentZig, UserRoleDocker, UserRoleEditor, UserRoleEza, UserRoleFastfetch, UserRoleFlameshot, UserRoleFonts, UserRoleFzf, UserRoleGdb, UserRoleGit, UserRoleHtop, UserRoleLldb, UserRoleNeovim, UserRoleNix, UserRoleOhMyPosh, UserRolePager, UserRoleRanger, UserRoleRedshift, UserRoleRipgrep, UserRoleRofi, UserRoleRts, UserRoleScripts, UserRoleShell, UserRoleSsh, UserRoleStarship, UserRoleSxhkd, UserRoleTerminal, UserRoleTheme, UserRoleTmux, UserRoleVscode, UserRoleXdg, UserRoleZoxide, UserRoleZsh}

var _UserRoleNameToValueMap = map[string]UserRole{
	_UserRoleName[0:9]:          UserRoleBootstrap,
	_UserRoleLowerName[0:9]:     UserRoleBootstrap,
	_UserRoleName[9:18]:         UserRoleAlacritty,
	_UserRoleLowerName[9:18]:    UserRoleAlacritty,
	_UserRoleName[18:22]:        UserRoleBash,
	_UserRoleLowerName[18:22]:   UserRoleBash,
	_UserRoleName[22:25]:        UserRoleBat,
	_UserRoleLowerName[22:25]:   UserRoleBat,
	_UserRoleName[25:30]:        UserRoleBrave,
	_UserRoleLowerName[25:30]:   UserRoleBrave,
	_UserRoleName[30:37]:        UserRoleBrowser,
	_UserRoleLowerName[30:37]:   UserRoleBrowser,
	_UserRoleName[37:41]:        UserRoleBtop,
	_UserRoleLowerName[37:41]:   UserRoleBtop,
	_UserRoleName[41:52]:        UserRoleDevelopment,
	_UserRoleLowerName[41:52]:   UserRoleDevelopment,
	_UserRoleName[52:67]:        UserRoleDevelopmentCpp,
	_UserRoleLowerName[52:67]:   UserRoleDevelopmentCpp,
	_UserRoleName[67:84]:        UserRoleDevelopmentDhall,
	_UserRoleLowerName[67:84]:   UserRoleDevelopmentDhall,
	_UserRoleName[84:102]:       UserRoleDevelopmentElixir,
	_UserRoleLowerName[84:102]:  UserRoleDevelopmentElixir,
	_UserRoleName[102:119]:      UserRoleDevelopmentGleam,
	_UserRoleLowerName[102:119]: UserRoleDevelopmentGleam,
	_UserRoleName[119:133]:      UserRoleDevelopmentGo,
	_UserRoleLowerName[119:133]: UserRoleDevelopmentGo,
	_UserRoleName[133:152]:      UserRoleDevelopmentHaskell,
	_UserRoleLowerName[133:152]: UserRoleDevelopmentHaskell,
	_UserRoleName[152:168]:      UserRoleDevelopmentJava,
	_UserRoleLowerName[152:168]: UserRoleDevelopmentJava,
	_UserRoleName[168:186]:      UserRoleDevelopmentKotlin,
	_UserRoleLowerName[168:186]: UserRoleDevelopmentKotlin,
	_UserRoleName[186:201]:      UserRoleDevelopmentLua,
	_UserRoleLowerName[186:201]: UserRoleDevelopmentLua,
	_UserRoleName[201:219]:      UserRoleDevelopmentNickel,
	_UserRoleLowerName[201:219]: UserRoleDevelopmentNickel,
	_UserRoleName[219:234]:      UserRoleDevelopmentNix,
	_UserRoleLowerName[219:234]: UserRoleDevelopmentNix,
	_UserRoleName[234:252]:      UserRoleDevelopmentNodejs,
	_UserRoleLowerName[234:252]: UserRoleDevelopmentNodejs,
	_UserRoleName[252:274]:      UserRoleDevelopmentPurescript,
	_UserRoleLowerName[252:274]: UserRoleDevelopmentPurescript,
	_UserRoleName[274:292]:      UserRoleDevelopmentPython,
	_UserRoleLowerName[274:292]: UserRoleDevelopmentPython,
	_UserRoleName[292:308]:      UserRoleDevelopmentRust,
	_UserRoleLowerName[292:308]: UserRoleDevelopmentRust,
	_UserRoleName[308:325]:      UserRoleDevelopmentShell,
	_UserRoleLowerName[308:325]: UserRoleDevelopmentShell,
	_UserRoleName[325:340]:      UserRoleDevelopmentZig,
	_UserRoleLowerName[325:340]: UserRoleDevelopmentZig,
	_UserRoleName[340:346]:      UserRoleDocker,
	_UserRoleLowerName[340:346]: UserRoleDocker,
	_UserRoleName[346:352]:      UserRoleEditor,
	_UserRoleLowerName[346:352]: UserRoleEditor,
	_UserRoleName[352:355]:      UserRoleEza,
	_UserRoleLowerName[352:355]: UserRoleEza,
	_UserRoleName[355:364]:      UserRoleFastfetch,
	_UserRoleLowerName[355:364]: UserRoleFastfetch,
	_UserRoleName[364:373]:      UserRoleFlameshot,
	_UserRoleLowerName[364:373]: UserRoleFlameshot,
	_UserRoleName[373:378]:      UserRoleFonts,
	_UserRoleLowerName[373:378]: UserRoleFonts,
	_UserRoleName[378:381]:      UserRoleFzf,
	_UserRoleLowerName[378:381]: UserRoleFzf,
	_UserRoleName[381:384]:      UserRoleGdb,
	_UserRoleLowerName[381:384]: UserRoleGdb,
	_UserRoleName[384:387]:      UserRoleGit,
	_UserRoleLowerName[384:387]: UserRoleGit,
	_UserRoleName[387:391]:      UserRoleHtop,
	_UserRoleLowerName[387:391]: UserRoleHtop,
	_UserRoleName[391:395]:      UserRoleLldb,
	_UserRoleLowerName[391:395]: UserRoleLldb,
	_UserRoleName[395:401]:      UserRoleNeovim,
	_UserRoleLowerName[395:401]: UserRoleNeovim,
	_UserRoleName[401:404]:      UserRoleNix,
	_UserRoleLowerName[401:404]: UserRoleNix,
	_UserRoleName[404:414]:      UserRoleOhMyPosh,
	_UserRoleLowerName[404:414]: UserRoleOhMyPosh,
	_UserRoleName[414:419]:      UserRolePager,
	_UserRoleLowerName[414:419]: UserRolePager,
	_UserRoleName[419:425]:      UserRoleRanger,
	_UserRoleLowerName[419:425]: UserRoleRanger,
	_UserRoleName[425:433]:      UserRoleRedshift,
	_UserRoleLowerName[425:433]: UserRoleRedshift,
	_UserRoleName[433:440]:      UserRoleRipgrep,
	_UserRoleLowerName[433:440]: UserRoleRipgrep,
	_UserRoleName[440:444]:      UserRoleRofi,
	_UserRoleLowerName[440:444]: UserRoleRofi,
	_UserRoleName[444:447]:      UserRoleRts,
	_UserRoleLowerName[444:447]: UserRoleRts,
	_UserRoleName[447:454]:      UserRoleScripts,
	_UserRoleLowerName[447:454]: UserRoleScripts,
	_UserRoleName[454:459]:      UserRoleShell,
	_UserRoleLowerName[454:459]: UserRoleShell,
	_UserRoleName[459:462]:      UserRoleSsh,
	_UserRoleLowerName[459:462]: UserRoleSsh,
	_UserRoleName[462:470]:      UserRoleStarship,
	_UserRoleLowerName[462:470]: UserRoleStarship,
	_UserRoleName[470:475]:      UserRoleSxhkd,
	_UserRoleLowerName[470:475]: UserRoleSxhkd,
	_UserRoleName[475:483]:      UserRoleTerminal,
	_UserRoleLowerName[475:483]: UserRoleTerminal,
	_UserRoleName[483:488]:      UserRoleTheme,
	_UserRoleLowerName[483:488]: UserRoleTheme,
	_UserRoleName[488:492]:      UserRoleTmux,
	_UserRoleLowerName[488:492]: UserRoleTmux,
	_UserRoleName[492:498]:      UserRoleVscode,
	_UserRoleLowerName[492:498]: UserRoleVscode,
	_UserRoleName[498:501]:      UserRoleXdg,
	_UserRoleLowerName[498:501]: UserRoleXdg,
	_UserRoleName[501:507]:      UserRoleZoxide,
	_UserRoleLowerName[501:507]: UserRoleZoxide,
	_UserRoleName[507:510]:      UserRoleZsh,
	_UserRoleLowerName[507:510]: UserRoleZsh,
}

var _UserRoleNames = []string{
	_UserRoleName[0:9],
	_UserRoleName[9:18],
	_UserRoleName[18:22],
	_UserRoleName[22:25],
	_UserRoleName[25:30],
	_UserRoleName[30:37],
	_UserRoleName[37:41],
	_UserRoleName[41:52],
	_UserRoleName[52:67],
	_UserRoleName[67:84],
	_UserRoleName[84:102],
	_UserRoleName[102:119],
	_UserRoleName[119:133],
	_UserRoleName[133:152],
	_UserRoleName[152:168],
	_UserRoleName[168:186],
	_UserRoleName[186:201],
	_UserRoleName[201:219],
	_UserRoleName[219:234],
	_UserRoleName[234:252],
	_UserRoleName[252:274],
	_UserRoleName[274:292],
	_UserRoleName[292:308],
	_UserRoleName[308:325],
	_UserRoleName[325:340],
	_UserRoleName[340:346],
	_UserRoleName[346:352],
	_UserRoleName[352:355],
	_UserRoleName[355:364],
	_UserRoleName[364:373],
	_UserRoleName[373:378],
	_UserRoleName[378:381],
	_UserRoleName[381:384],
	_UserRoleName[384:387],
	_UserRoleName[387:391],
	_UserRoleName[391:395],
	_UserRoleName[395:401],
	_UserRoleName[401:404],
	_UserRoleName[404:414],
	_UserRoleName[414:419],
	_UserRoleName[419:425],
	_UserRoleName[425:433],
	_UserRoleName[433:440],
	_UserRoleName[440:444],
	_UserRoleName[444:447],
	_UserRoleName[447:454],
	_UserRoleName[454:459],
	_UserRoleName[459:462],
	_UserRoleName[462:470],
	_UserRoleName[470:475],
	_UserRoleName[475:483],
	_UserRoleName[483:488],
	_UserRoleName[488:492],
	_UserRoleName[492:498],
	_UserRoleName[498:501],
	_UserRoleName[501:507],
	_UserRoleName[507:510],
}

// UserRoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func UserRoleString(s string) (UserRole, error) {
	if val, ok := _UserRoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _UserRoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to UserRole values", s)
}

// UserRoleValues returns all values of the enum
func UserRoleValues() []UserRole {
	return _UserRoleValues
}

// UserRoleStrings returns a slice of all String values of the enum
func UserRoleStrings() []string {
	strs := make([]string, len(_UserRoleNames))
	copy(strs, _UserRoleNames)
	return strs
}

// IsAUserRole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i UserRole) IsAUserRole() bool {
	for _, v := range _UserRoleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for UserRole
func (i UserRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for UserRole
func (i *UserRole) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("UserRole should be a string, got %s", data)
	}

	var err error
	*i, err = UserRoleString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for UserRole
func (i UserRole) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for UserRole
func (i *UserRole) UnmarshalText(text []byte) error {
	var err error
	*i, err = UserRoleString(string(text))
	return err
}
