// Code generated by "marshaler -type UserRole -stringer NixString"; DO NOT EDIT.
package role

import "encoding/json"

// MarshalJSON implements the json.Marshaler interface for UserRole
func (i UserRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.NixString())
}

// MarshalText implements the encoding.TextMarshaler interface for UserRole
func (i UserRole) MarshalText() ([]byte, error) {
	return []byte(i.NixString()), nil
}
