---
# tasks file for roles/xinit

- name: Create xinit config directory
  become: yes
  become_user: "{{ user_id }}"
  file:
    path: "{{ user_home_dir }}"
    state: directory

- name: Copy xinit config files
  become: yes
  become_user: "{{ user_id }}"
  copy:
    src: "{{ item }}"
    dest: "{{ user_home_dir }}/.{{ item }}"
    force: yes
  loop:
    - xinitrc
