---
# tasks file for roles/xinit

- name: Create xinit config directory
  become: yes
  become_user: "{{ user_id }}"
  file:
    path: "{{ user_home_dir }}"
    state: directory

- name: Generate xinit config files
  become: yes
  become_user: "{{ user_id }}"
  template:
    src: "{{ item }}.j2"
    dest: "{{ user_home_dir }}/.{{ item }}"
    force: yes
  loop:
    - xinitrc
