{
  config,
  lib,
  pkgs,
  env,
  ...
}:
{
  imports = lib.flatten [
    ./roles/bootstrap.nix
    ./roles/boot.nix
    ./roles/chocolatey.nix
    ./roles/cockpit.nix
    ./roles/docker.nix
    ./roles/garuda.nix
    ./roles/glazewm.nix
    ./roles/home-manager.nix
    ./roles/hyprland.nix
    ./roles/i18n.nix
    ./roles/kde.nix
    ./roles/kernel.nix
    ./roles/monitoring.nix
    ./roles/motd.nix
    ./roles/networking.nix
    ./roles/nix.nix
    ./roles/openssh.nix
    ./roles/shell.nix
    ./roles/sudo.nix
    ./roles/time.nix
    ./roles/udisks2.nix
    ./roles/user.nix
    ./roles/winget.nix
    ./roles/wsl.nix
    ./roles/xserver.nix
    ./roles/xrdp.nix
    ./roles/zram.nix
  ];
}
