// Code generated by generator; DO NOT EDIT.
package themes

import (
	enums "github.com/hanselrd/dotfiles/lib/enums"
	structs "github.com/hanselrd/dotfiles/lib/structs"
)

var ThemeMapStruct = map[enums.Theme]structs.Theme{
	enums.ThemeChalk:     Chalk,
	enums.ThemeGrayscale: Grayscale,
	enums.ThemeMatrix:    Matrix,
	enums.ThemeMocha:     Mocha,
	enums.ThemeOcean:     Ocean,
	enums.ThemeOneDark:   OneDark,
	enums.ThemeTomorrow:  Tomorrow,
	enums.ThemeTwilight:  Twilight,
}
