//go:build ignore

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	. "github.com/dave/jennifer/jen"

	"github.com/hanselrd/dotfiles/lib/enums"
	"github.com/hanselrd/dotfiles/lib/utils"
)

func main() {
	goPackage := os.Getenv("GOPACKAGE")

	f := NewFile(goPackage)

	f.PackageComment("Code generated by generator; DO NOT EDIT.")

	f.Var().Id("ThemeMapStruct").
		Op("=").Map(Qual("github.com/hanselrd/dotfiles/lib/enums", "Theme")).
		Qual("github.com/hanselrd/dotfiles/lib/structs", "Theme").Values(
		DictFunc(func(d Dict) {
			for _, theme := range enums.Themes() {
				d[Qual("github.com/hanselrd/dotfiles/lib/enums", fmt.Sprintf("Theme%s", strings.ReplaceAll(utils.Caser.Title.String(theme.String()), "-", "")))] = Id(
					strings.ReplaceAll(utils.Caser.Title.String(theme.String()), "-", ""),
				)
			}
		}))

	goFile := os.Getenv("GOFILE")
	ext := filepath.Ext(goFile)
	baseFilename := goFile[0 : len(goFile)-len(ext)]
	targetFilename := baseFilename + "_gen.go"

	f.Save(targetFilename)
}
