---
# tasks file for roles/urxvt

- name: Create urxvt cache directory
  become: yes
  become_user: "{{ user_id }}"
  file:
    path: "{{ user_cache_dir }}/dotfiles/urxvt"
    state: directory

- name: Clone urxvt-font-size
  become: yes
  become_user: "{{ user_id }}"
  git:
    repo: https://github.com/majutsushi/urxvt-font-size
    dest: "{{ user_cache_dir }}/dotfiles/urxvt/urxvt-font-size"
    update: yes

- name: Create urxvt extension directory
  become: yes
  become_user: "{{ user_id }}"
  file:
    path: "{{ user_home_dir }}/.urxvt/ext"
    state: directory

- name: Copy urxvt-font-size
  become: yes
  become_user: "{{ user_id }}"
  copy:
    src: "{{ user_cache_dir }}/dotfiles/urxvt/urxvt-font-size/font-size"
    dest: "{{ user_home_dir }}/.urxvt/ext/font-size"
    force: yes
