import { env_var_set } from "std/env"
import { join } from "std/text"

fun nix_config_option(name: Text, values: [Text]): Text {
    return "{name} = {join(values, " ")}"
}

main {
    const nix_config = [
        nix_config_option("experimental-features", ["nix-command", "flakes", "pipe-operators"]),
        nix_config_option("show-trace", ["true"])
    ]

    env_var_set("NIX_CONFIG", join(nix_config, "\n"))?
}
