//go:build ignore

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/dave/jennifer/jen"

	"github.com/hanselrd/dotfiles/pkg/nix"
)

func main() {
	goPackage := os.Getenv("GOPACKAGE")

	f := jen.NewFile(goPackage)

	f.PackageComment("Code generated by \"generator\"; DO NOT EDIT.")

	f.Type().DefsFunc(func(g *jen.Group) {
		for _, moduleType := range nix.ModuleTypeValues() {
			g.Id(fmt.Sprintf("%sModule", moduleType)).
				Interface(
					jen.Id("Module"),
					jen.Id(fmt.Sprintf("%sModuleTag", strings.ToLower(moduleType.String()))).
						Params(),
				)
		}
	})

	for _, moduleType := range nix.ModuleTypeValues() {
		for _, moduleString := range nix.ModuleStrings(moduleType) {
			f.Func().
				Params(jen.Id("m").Id(fmt.Sprintf("%sModule%s", moduleType, moduleString))).
				Id("String").
				Params().
				String().
				Block(jen.Return(jen.Id(fmt.Sprintf("%sModule%s", strings.ToLower(moduleType.String()), moduleString)).Dot("String").Call()))

			f.Func().
				Params(jen.Id("m").Id(fmt.Sprintf("%sModule%s", moduleType, moduleString))).
				Id("NixString").
				Params().
				String().
				Block(jen.Return(jen.Id(fmt.Sprintf("%sModule%s", strings.ToLower(moduleType.String()), moduleString)).Dot("NixString").Call()))

			f.Func().
				Params(jen.Id("m").Id(fmt.Sprintf("%sModule%s", moduleType, moduleString))).
				Id("Type").
				Params().
				Id("ModuleType").
				Block(jen.Return(jen.Id(fmt.Sprintf("ModuleType%s", moduleType))))

			f.Func().
				Params(jen.Id("m").Id(fmt.Sprintf("%sModule%s", moduleType, moduleString))).
				Id("Encryption").
				Params().
				Qual("github.com/hanselrd/dotfiles/internal/encryption", "Encryption").
				Block(jen.Return(jen.Id(fmt.Sprintf("%sModule%s", strings.ToLower(moduleType.String()), moduleString)).Dot("Encryption").Call()))

			f.Func().
				Params(jen.Id("m").Id(fmt.Sprintf("%sModule%s", moduleType, moduleString))).
				Id("moduleTag").
				Params().
				Block()

			f.Func().
				Params(jen.Id("m").Id(fmt.Sprintf("%sModule%s", moduleType, moduleString))).
				Id(fmt.Sprintf("%sModuleTag", strings.ToLower(moduleType.String()))).
				Params().
				Block()
		}
	}

	f.Var().DefsFunc(func(g *jen.Group) {
		for _, moduleType := range nix.ModuleTypeValues() {
			for _, moduleString := range nix.ModuleStrings(moduleType) {
				g.Id("_").
					Id(fmt.Sprintf("%sModule", moduleType)).
					Op("=").
					Id(fmt.Sprintf("%sModule%s", moduleType, moduleString)).
					Values()
			}
		}
	})

	goFile := os.Getenv("GOFILE")
	ext := filepath.Ext(goFile)
	baseFilename := goFile[0 : len(goFile)-len(ext)]
	targetFilename := baseFilename + "_generated.go"

	f.Save(targetFilename)
}
