//go:build ignore

package main

import (
	"fmt"
	"os"
	"path/filepath"

	. "github.com/dave/jennifer/jen"

	"github.com/hanselrd/dotfiles/pkg/profile"
)

func main() {
	goPackage := os.Getenv("GOPACKAGE")

	f := NewFile(goPackage)

	f.PackageComment("Code generated by \"generator\"; DO NOT EDIT.")

	f.Var().DefsFunc(func(g *Group) {
		for _, systemProfile := range profile.SystemProfileValues() {
			for _, userProfile := range profile.UserProfileValues() {
				g.Id(fmt.Sprintf("%s%s", systemProfile, userProfile)).
					Op("=").
					Id("NewProfileGroup").
					Call(
						Id(fmt.Sprintf("SystemProfile%s", systemProfile)),
						Id(
							fmt.Sprintf("UserProfile%s", userProfile),
						),
					)
			}
		}
	})

	f.Var().DefsFunc(func(g *Group) {
		for _, systemProfile := range profile.SystemProfileValues() {
			g.Id(fmt.Sprintf("%sProfiles", systemProfile)).
				Op("=").
				Index().
				Id("ProfileGroup").
				ValuesFunc(func(gg *Group) {
					for _, userProfile := range profile.UserProfileValues() {
						gg.Id(
							fmt.Sprintf(
								"%s%s",
								systemProfile,
								userProfile,
							),
						)
					}
				})
		}
		g.Id("HomeManagerProfiles").Op("=").Qual("slices", "Concat").CallFunc(func(gg *Group) {
			for _, systemProfile := range profile.SystemProfileValues() {
				gg.Id(fmt.Sprintf("%sProfiles", systemProfile))
			}
		})
	})

	goFile := os.Getenv("GOFILE")
	ext := filepath.Ext(goFile)
	baseFilename := goFile[0 : len(goFile)-len(ext)]
	targetFilename := baseFilename + "_gen.go"

	f.Save(targetFilename)
}
