// Code generated by "nixstringee SystemProfile"; DO NOT EDIT.
package profile

import "encoding/json"

// MarshalJSON implements the json.Marshaler interface for SystemProfile
func (i SystemProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.NixString())
}

// MarshalText implements the encoding.TextMarshaler interface for SystemProfile
func (i SystemProfile) MarshalText() ([]byte, error) {
	return []byte(i.NixString()), nil
}
