// Code generated by "marshaler -type UserProfile -stringer NixString"; DO NOT EDIT.
package profile

import "encoding/json"

// MarshalJSON implements the json.Marshaler interface for UserProfile
func (i UserProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.NixString())
}

// MarshalText implements the encoding.TextMarshaler interface for UserProfile
func (i UserProfile) MarshalText() ([]byte, error) {
	return []byte(i.NixString()), nil
}
