{
  config,
  lib,
  pkgs,
  env,
  ...
}: {
  imports = lib.flatten [
    ./roles/bootstrap.nix
    ./roles/alacritty.nix
    ./roles/bash.nix
    ./roles/bat.nix
    ./roles/brave.nix
    ./roles/browser.nix
    ./roles/btop.nix
    ./roles/development.nix
    ./roles/development.cpp.nix
    ./roles/development.dhall.nix
    ./roles/development.elixir.nix
    ./roles/development.gleam.nix
    ./roles/development.go.nix
    ./roles/development.haskell.nix
    ./roles/development.java.nix
    ./roles/development.kotlin.nix
    ./roles/development.lua.nix
    ./roles/development.nickel.nix
    ./roles/development.nix.nix
    ./roles/development.nodejs.nix
    ./roles/development.purescript.nix
    ./roles/development.python.nix
    ./roles/development.rust.nix
    ./roles/development.shell.nix
    ./roles/development.zig.nix
    ./roles/docker.nix
    ./roles/editor.nix
    ./roles/eza.nix
    ./roles/fonts.nix
    ./roles/fzf.nix
    ./roles/gdb.nix
    ./roles/git.nix
    ./roles/htop.nix
    ./roles/neovim.nix
    ./roles/nix.nix
    ./roles/oh-my-posh.nix
    ./roles/pager.nix
    ./roles/ranger.nix
    ./roles/ripgrep.nix
    (lib.optional (!env.extra.encrypted.default) ../secrets/user/roles/rts.nix)
    ./roles/scripts.nix
    ./roles/shell.nix
    ./roles/ssh.nix
    ./roles/starship.nix
    ./roles/terminal.nix
    ./roles/theme.nix
    ./roles/tmux.nix
    ./roles/vscode.nix
    ./roles/xdg.nix
    ./roles/zoxide.nix
    ./roles/zsh.nix
  ];
}
