  # sudo ansible-playbook ansible-playbooks/main.yml --extra-vars "@template/home/extra-vars.yml"

- hosts: localhost
  gather_facts: no

  tasks:
      # - name: "Enable nforro/i3-gaps repo"
      #   become: yes
      #   command: dnf copr enable nforro/i3-gaps -y
      #   register: output
      # - debug:
      #     var: output.stdout_lines

      # - name: "Enable jstanek/ports repo"
      #   become: yes
      #   command: dnf copr enable jstanek/ports -y
      #   register: output
      # - debug:
      #     var: output.stdout_lines

      # - name: "Enable balamurali27/betterlockscreen repo"
      #   become: yes
      #   command: dnf copr enable balamurali27/betterlockscreen -y
      #   register: output
      # - debug:
      #     var: output.stdout_lines

      - name: Install packages
        become: yes
        dnf:
            name:
                # - ImageMagick
                # - SDL2-devel
                # - SDL2_image-devel
                # - SDL2_mixer-devel
                # - SDL2_net-devel
                # - SDL2_ttf-devel
                # - alsa-lib-devel
                # - autoconf
                # - automake
                # - cairo-devel
                # - dmenu
                # - jsoncpp-devel
                # - libcurl-devel
                # - libmpdclient-devel
                # - libnl3-devel
                # - pulseaudio-libs-devel
                # - pulseaudio-utils
                # - scrot
                # - tiled
                # - tlp
                # - tlp-rdw
                # - valgrind
                # - wireless-tools-devel
                # - xcb-proto
                # - xcb-util-cursor-devel
                # - xcb-util-devel
                # - xcb-util-image-devel
                # - xcb-util-wm-devel
                # - xcb-util-xrm-devel
                # - xrandr
                - arandr
                - betterlockscreen
                - clang
                - clang-tools-extra
                - cmake
                - compton
                - ctags
                - feh
                - gcc-g++
                - htop
                - i3-gaps
                - i3-ipc
                - i3status
                - neofetch
                - network-manager-applet
                - ninja-build
                - openvpn
                - ranger
                - redshift
                - rofi
                - rpmconf
                - rxvt-unicode-256color
                - symlinks
                - tmux
                - vim-enhanced
                - xbacklight
                - xclip
                - zsh
            state: present

      - name: Upgrade all packages
        become: yes
        dnf:
            name: "*"
            state: latest

      - name: Git checkout Tmux Plugin Manager
        become: yes
        become_user: "{{ dotfiles_user }}"
        git:
            repo: https://github.com/tmux-plugins/tpm.git
            dest: ~/.tmux/plugins/tpm

      - name: Git checkout Oh My Zsh
        become: yes
        become_user: "{{ dotfiles_user }}"
        git:
            repo: https://github.com/ohmyzsh/ohmyzsh.git
            dest: ~/.oh-my-zsh

      - name: Git checkout zsh-autosuggestions
        become: yes
        become_user: "{{ dotfiles_user }}"
        git:
            repo: https://github.com/zsh-users/zsh-autosuggestions.git
            dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

      - name: "Git checkout dotfiles to {{ dotfiles_user }}'s ~/.dotfiles"
        become: yes
        become_user: "{{ dotfiles_user }}"
        git:
            repo: https://github.com/hanselrd/dotfiles.git
            dest: ~/.dotfiles
            update: no

      - name: "Copy ~/.dotfiles/template/root to /"
        become: yes
        copy:
            src: "/home/{{ dotfiles_user }}/.dotfiles/template/{{ item.src }}"
            dest: "{{ item.dest }}"
            remote_src: yes
            force: yes
        loop:
            - { src: root/etc/X11/xorg.conf, dest: /etc/X11/xorg.conf }

      - name: "Symlink ~/.dotfiles/template/home to ~"
        become: yes
        become_user: "{{ dotfiles_user }}"
        file:
            src: "~/.dotfiles/template/{{ item.src }}"
            dest: "{{ item.dest }}"
            state: link
            force: yes
        loop:
            # - { src: home/Xresources, dest: ~/.Xresources }
            # - { src: home/config/i3/config, dest: ~/.config/i3/config }
            # - { src: home/config/i3status/config, dest: ~/.config/i3status/config }
            # - { src: home/config/xfce4/terminal/terminalrc, dest: ~/.config/xfce4/terminal/terminalrc }
            - { src: home/backgrounds, dest: ~/.backgrounds }
            - { src: home/compton.conf, dest: ~/.compton.conf }
            - { src: home/config/gtk-3.0/bookmarks, dest: ~/.config/gtk-3.0/bookmarks }
            - { src: home/config/gtk-3.0/settings.ini, dest: ~/.config/gtk-3.0/settings.ini }
            - { src: home/config/polybar/config, dest: ~/.config/polybar/config }
            - { src: home/config/polybar/launch.sh, dest: ~/.config/polybar/launch.sh }
            - { src: home/config/ranger/rc.conf, dest: ~/.config/ranger/rc.conf }
            - { src: home/config/rofi/config, dest: ~/.config/rofi/config }
            - { src: home/fonts, dest: ~/.fonts }
            - { src: home/gdb, dest: ~/.gdb }
            - { src: home/gdbinit, dest: ~/.gdbinit }
            - { src: home/gtkrc-2.0, dest: ~/.gtkrc-2.0 }
            - { src: home/tmux.conf, dest: ~/.tmux.conf }
            - { src: home/tmux.line, dest: ~/.tmux.line }
            - { src: home/urxvt, dest: ~/.urxvt }
            - { src: home/vimrc, dest: ~/.vimrc }
            - { src: home/zshrc, dest: ~/.zshrc }

      - name: "Generate files"
        become: yes
        become_user: "{{ dotfiles_user }}"
        template:
            src: "/home/{{ dotfiles_user }}/.dotfiles/template/{{ item.src }}"
            dest: "{{ item.dest }}"
            force: yes
        loop:
            # - { src: home/gitconfig.j2, dest: ~/.gitconfig }
            - { src: home/Xresources.j2, dest: ~/.Xresources }
            - { src: home/config/i3/config.j2, dest: ~/.config/i3/config }
            - { src: home/config/i3status/config.j2, dest: ~/.config/i3status/config }
            - { src: home/config/xfce4/terminal/terminalrc.j2, dest: ~/.config/xfce4/terminal/terminalrc }
            - { src: home/extra-vars.yml, dest: ~/.extra-vars.yml }
