  # sudo ansible-playbook $HOME/.dotfiles/ansible-playbooks/main.yml --extra-vars "@$HOME/.dotfiles/template/home/dotfiles-vars.yml"

- hosts: localhost
  gather_facts: no

  tasks:
      - name: Enable COPR repos
        become: yes
        command: "dnf copr enable {{ item }} -y"
        register: output
        loop:
            - balamurali27/betterlockscreen
            - jstanek/ports
            - nforro/i3-gaps
      - debug:
            msg: "{{ item.stdout_lines }}"
        with_items: "{{ output.results }}"

      - name: Install packages
        become: yes
        dnf:
            name:
                # - ImageMagick
                # - SDL2-devel
                # - SDL2_image-devel
                # - SDL2_mixer-devel
                # - SDL2_net-devel
                # - SDL2_ttf-devel
                # - alsa-lib-devel
                # - autoconf
                # - automake
                # - cairo-devel
                # - dmenu
                # - jsoncpp-devel
                # - libcurl-devel
                # - libmpdclient-devel
                # - libnl3-devel
                # - pulseaudio-libs-devel
                # - pulseaudio-utils
                # - scrot
                # - tiled
                # - tlp
                # - tlp-rdw
                # - valgrind
                # - wireless-tools-devel
                # - xcb-proto
                # - xcb-util-cursor-devel
                # - xcb-util-devel
                # - xcb-util-image-devel
                # - xcb-util-wm-devel
                # - xcb-util-xrm-devel
                # - xrandr
                - arandr
                - betterlockscreen
                - brightlight
                - clang
                - clang-tools-extra
                - cmake
                - compton
                - ctags
                - feh
                - flameshot
                - gcc-g++
                - htop
                - i3-gaps
                - i3-ipc
                - i3status
                - neofetch
                - network-manager-applet
                - ninja-build
                - openvpn
                - ranger
                - redshift
                - rofi
                - rpmconf
                - rxvt-unicode-256color
                - symlinks
                - tmux
                - vim-enhanced
                - xclip
                - zsh
            state: present

      - name: Upgrade all packages
        become: yes
        dnf:
            name: "*"
            state: latest

      - name: Git checkout repos
        become: yes
        become_user: "{{ dotfiles_user }}"
        git:
            repo: "{{ item.repo }}"
            dest: "{{ item.dest }}"
            update: "{{ item.update | bool }}"
        loop:
            - { repo: "https://github.com/hanselrd/dotfiles.git", dest: ~/.dotfiles, update: no }
            - { repo: "https://github.com/ohmyzsh/ohmyzsh.git", dest: ~/.oh-my-zsh, update: yes }
            - { repo: "https://github.com/tmux-plugins/tpm.git", dest: ~/.tmux/plugins/tpm, update: yes }
            - { repo: "https://github.com/zsh-users/zsh-autosuggestions.git", dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions, update: yes }

      # - name: Create directories in / before copy
      #   become: yes
      #   file:
      #       path: "{{ item }}"
      #       state: directory
      #   loop:
      #       - /etc/X11

      # - name: Copy ~/.dotfiles/template/root to /
      #   become: yes
      #   copy:
      #       src: "/home/{{ dotfiles_user }}/.dotfiles/template/{{ item.src }}"
      #       dest: "{{ item.dest }}"
      #       remote_src: yes
      #       force: yes
      #   loop:
      #       - { src: root/etc/X11/xorg.conf, dest: /etc/X11/xorg.conf }

      - name: Create directories in ~ before symlink
        become: yes
        become_user: "{{ dotfiles_user }}"
        file:
            path: "{{ item }}"
            state: directory
        loop:
            # - ~/.config/polybar
            - ~/.config/gtk-3.0
            - ~/.config/ranger
            - ~/.config/rofi

      - name: Symlink ~/.dotfiles/template/home to ~
        become: yes
        become_user: "{{ dotfiles_user }}"
        file:
            src: "~/.dotfiles/template/{{ item.src }}"
            dest: "{{ item.dest }}"
            state: link
            force: yes
        loop:
            # - { src: home/config/polybar/config, dest: ~/.config/polybar/config }
            # - { src: home/config/polybar/launch.sh, dest: ~/.config/polybar/launch.sh }
            - { src: home/backgrounds, dest: ~/.backgrounds }
            - { src: home/compton.conf, dest: ~/.compton.conf }
            - { src: home/config/gtk-3.0/bookmarks, dest: ~/.config/gtk-3.0/bookmarks }
            - { src: home/config/gtk-3.0/settings.ini, dest: ~/.config/gtk-3.0/settings.ini }
            - { src: home/config/ranger/rc.conf, dest: ~/.config/ranger/rc.conf }
            - { src: home/config/rofi/config, dest: ~/.config/rofi/config }
            - { src: home/fonts, dest: ~/.fonts }
            - { src: home/gdb, dest: ~/.gdb }
            - { src: home/gdbinit, dest: ~/.gdbinit }
            - { src: home/gtkrc-2.0, dest: ~/.gtkrc-2.0 }
            - { src: home/scripts, dest: ~/.scripts }
            - { src: home/tmux.conf, dest: ~/.tmux.conf }
            - { src: home/tmux.line, dest: ~/.tmux.line }
            - { src: home/urxvt, dest: ~/.urxvt }
            - { src: home/vimrc, dest: ~/.vimrc }
            - { src: home/zshrc, dest: ~/.zshrc }

      - name: Create directories in ~ before generate
        become: yes
        become_user: "{{ dotfiles_user }}"
        file:
            path: "{{ item }}"
            state: directory
        loop:
            - ~/.config/i3
            - ~/.config/i3status
            - ~/.config/rofi
            - ~/.config/xfce4/terminal

      - name: Generate files
        become: yes
        become_user: "{{ dotfiles_user }}"
        template:
            src: "/home/{{ dotfiles_user }}/.dotfiles/template/{{ item.src }}"
            dest: "{{ item.dest }}"
            force: yes
        loop:
            # - { src: home/gitconfig.j2, dest: ~/.gitconfig }
            - { src: home/Xresources.j2, dest: ~/.Xresources }
            - { src: home/Xresources.j2, dest: ~/.dotfiles/template/home/Xresources } # copy
            - { src: home/config/i3/config.j2, dest: ~/.config/i3/config }
            - { src: home/config/i3/config.j2, dest: ~/.dotfiles/template/home/config/i3/config } # copy
            - { src: home/config/i3status/config-sm.j2, dest: ~/.config/i3status/config-sm }
            - { src: home/config/i3status/config-sm.j2, dest: ~/.dotfiles/template/home/config/i3status/config-sm } # copy
            - { src: home/config/i3status/config.j2, dest: ~/.config/i3status/config }
            - { src: home/config/i3status/config.j2, dest: ~/.dotfiles/template/home/config/i3status/config } # copy
            - { src: home/config/rofi/theme.rasi.j2, dest: ~/.config/rofi/theme.rasi }
            - { src: home/config/rofi/theme.rasi.j2, dest: ~/.dotfiles/template/home/config/rofi/theme.rasi } # copy
            - { src: home/config/xfce4/terminal/terminalrc.j2, dest: ~/.config/xfce4/terminal/terminalrc }
            - { src: home/config/xfce4/terminal/terminalrc.j2, dest: ~/.dotfiles/template/home/config/xfce4/terminal/terminalrc } # copy
            - { src: home/dotfiles-vars.yml, dest: ~/.dotfiles-vars.yml }
