---
# tasks file for roles/fonts

- name: Create fonts directory
  file:
    path: "{{ user_root_dir }}/usr/local/share/fonts"
    state: directory

- name: Copy font files
  copy:
    src: "{{ item }}"
    dest: "{{ user_root_dir }}/usr/local/share/fonts/{{ item }}"
    force: yes
  loop:
    - iosevka-term-bold.ttf
    - iosevka-term-bolditalic.ttf
    - iosevka-term-boldoblique.ttf
    - iosevka-term-extended.ttf
    - iosevka-term-extendedbold.ttf
    - iosevka-term-extendedbolditalic.ttf
    - iosevka-term-extendedboldoblique.ttf
    - iosevka-term-extendedextrabold.ttf
    - iosevka-term-extendedextrabolditalic.ttf
    - iosevka-term-extendedextraboldoblique.ttf
    - iosevka-term-extendedextralight.ttf
    - iosevka-term-extendedextralightitalic.ttf
    - iosevka-term-extendedextralightoblique.ttf
    - iosevka-term-extendedheavy.ttf
    - iosevka-term-extendedheavyitalic.ttf
    - iosevka-term-extendedheavyoblique.ttf
    - iosevka-term-extendeditalic.ttf
    - iosevka-term-extendedlight.ttf
    - iosevka-term-extendedlightitalic.ttf
    - iosevka-term-extendedlightoblique.ttf
    - iosevka-term-extendedmedium.ttf
    - iosevka-term-extendedmediumitalic.ttf
    - iosevka-term-extendedmediumoblique.ttf
    - iosevka-term-extendedoblique.ttf
    - iosevka-term-extendedsemibold.ttf
    - iosevka-term-extendedsemibolditalic.ttf
    - iosevka-term-extendedsemiboldoblique.ttf
    - iosevka-term-extendedthin.ttf
    - iosevka-term-extendedthinitalic.ttf
    - iosevka-term-extendedthinoblique.ttf
    - iosevka-term-extrabold.ttf
    - iosevka-term-extrabolditalic.ttf
    - iosevka-term-extraboldoblique.ttf
    - iosevka-term-extralight.ttf
    - iosevka-term-extralightitalic.ttf
    - iosevka-term-extralightoblique.ttf
    - iosevka-term-heavy.ttf
    - iosevka-term-heavyitalic.ttf
    - iosevka-term-heavyoblique.ttf
    - iosevka-term-italic.ttf
    - iosevka-term-light.ttf
    - iosevka-term-lightitalic.ttf
    - iosevka-term-lightoblique.ttf
    - iosevka-term-medium.ttf
    - iosevka-term-mediumitalic.ttf
    - iosevka-term-mediumoblique.ttf
    - iosevka-term-oblique.ttf
    - iosevka-term-regular.ttf
    - iosevka-term-semibold.ttf
    - iosevka-term-semibolditalic.ttf
    - iosevka-term-semiboldoblique.ttf
    - iosevka-term-thin.ttf
    - iosevka-term-thinitalic.ttf
    - iosevka-term-thinoblique.ttf

- name: Create font cache directory
  become: yes
  become_user: "{{ user_id }}"
  file:
    path: "{{ user_cache_dir }}/dotfiles/fonts"
    state: directory

- name: "Generate font file using ({{ font_name }})"
  become: yes
  become_user: "{{ user_id }}"
  template:
    src: "{{ font_name }}.yml.j2"
    dest: "{{ user_cache_dir }}/dotfiles/fonts/{{ font_name }}.yml"
    force: yes

- name: Include font variables
  include_vars: "{{ user_cache_dir }}/dotfiles/fonts/{{ font_name }}.yml"

- name: Export font variables
  set_fact:
    font_name: "{{ font_name }}"
