---
# tasks file for roles/fonts

- name: Create fonts directory
  file:
    path: "{{ user_root_dir }}/usr/local/share/fonts"
    state: directory

- name: Extract font archive files
  unarchive:
    src: "{{ item }}"
    dest: "{{ user_root_dir }}/usr/local/share/fonts"
  loop:
    # - Iosevka.zip
    - CascadiaCode.zip
    - FantasqueSansMono.zip
    - Inconsolata.zip
    - JetBrainsMono.zip

- name: Create font cache directory
  become: yes
  become_user: "{{ user_id }}"
  file:
    path: "{{ user_cache_dir }}/dotfiles/fonts"
    state: directory

- name: "Generate font file using ({{ font_name }})"
  become: yes
  become_user: "{{ user_id }}"
  template:
    src: "{{ font_name }}.yml.j2"
    dest: "{{ user_cache_dir }}/dotfiles/fonts/{{ font_name }}.yml"
    force: yes

- name: Include font variables
  include_vars: "{{ user_cache_dir }}/dotfiles/fonts/{{ font_name }}.yml"

- name: Export font variables
  set_fact:
    font_name: "{{ font_name }}"
